<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ActivityAdd.aspx.cs" Inherits="CRM.BasicData.ActivityAdd" %>

<%@ Register Src="~/BasicData/common.ascx" TagPrefix="uc1" TagName="common" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <uc1:common runat="server" id="common" />
    <script src="JsDate.js"></script>

</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>

                <table style="width: 100%">
                    <tr>
                        <td style="vertical-align: top; ">

                            <div style="overflow: auto; width: 250px; height: 550px;border: solid 1px #ccc">
                                <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%"
                                    ShowLines="True" AutoGenerateDataBindings="False" OnSelectedNodeChanged="trv_menu_SelectedNodeChanged" ImageSet="XPFileExplorer">
                                    <ParentNodeStyle Font-Bold="False" />
                                    <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
                                    <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                                    <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                                        NodeSpacing="0px" VerticalPadding="0px" />
                                </asp:TreeView>
                            </div>

                        </td>
                        <td style="vertical-align: top">
                            <table class="table table-bordered table-condensed">
                                <tr>
                                    <td style="width: 60px;" class="right">钢种</td>
                                    <td style="width: 100px;">
                                        <input type="text" placeholder="钢种" style="width: 100px;" runat="server" id="txt_GRD" /></td>
                                    <td style="width: 80px;">规格区间</td>
                                    <td style="width: 220px;">
                                        <input type="text" placeholder="最小值" runat="server" id="txtSPEC1" style="width: 100px;" class="numJe" />~<input type="text" placeholder="最大值" runat="server" id="txtSPEC2" style="width: 100px;" class="numJe" />
                                    </td>
                                    <td>
                                        <asp:Button ID="btnSearch" runat="server" Text="查询" CssClass="btn btn-primary btn-xs btn_w60" OnClick="btnSearch_Click" />
                                        &nbsp;<asp:Button ID="btnclear" runat="server" Text="置空" CssClass="btn  btn-info btn-xs btn_w60" OnClick="btnclear_Click" />
                                    </td>
                                </tr>
                            </table>
                            <div>
                                <span class="red">分类：<asp:Literal ID="ltlC_PROD_NAME" runat="server"></asp:Literal>
                                    <asp:Literal ID="ltlgroupCode" Visible="false" runat="server"></asp:Literal></span>
                            </div>
                            <div style="overflow: auto; height: 440px;">
                                <table class="table table-bordered table-hover table-condensed">
                                    <thead>
                                        <tr>
                                            <th style="width:40px;">选择
                                            </th>

                                            <th>物料编码</th>
                                            <th>物料名称</th>
                                            <th>钢种</th>
                                            <th>规格</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <asp:Repeater ID="rptList" runat="server">
                                            <ItemTemplate>
                                                <tr>
                                                    <td>
                                                        <input id="chkSelect" class="che1" runat="server" type="checkbox" value='<%#DataBinder.Eval (Container.DataItem,"C_MAT_CODE") %>' /></td>

                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"C_MAT_CODE") %>
                                                    </td>
                                                    <td>
                                                        <asp:Literal ID="ltlC_MAT_NAME" Text='<%#DataBinder.Eval (Container.DataItem,"C_MAT_NAME") %>' runat="server"></asp:Literal>
                                                        <asp:Literal ID="ltlGroupCode" Visible="false" Text='<%#DataBinder.Eval (Container.DataItem,"C_MAT_GROUP_CODE") %>' runat="server"></asp:Literal>

                                                    </td>
                                                    <td>
                                                        <asp:Literal ID="ltlSTL_GRD" Text='<%#DataBinder.Eval (Container.DataItem,"C_STL_GRD") %>' runat="server"></asp:Literal></td>
                                                    <td>
                                                        <asp:Literal ID="ltlSPEC" Text='<%#DataBinder.Eval (Container.DataItem,"C_SPEC") %>' runat="server"></asp:Literal></td>
                                                </tr>
                                            </ItemTemplate>
                                        </asp:Repeater>
                                    </tbody>
                                </table>

                            </div>

                            <table class="table table-bordered">
                                <tr>
                                    <td>
                                        <input id="chxAll" type="checkbox" class="qx1" />全选</td>
                                   
                                    <td>
                                        <asp:DropDownList ID="dropAreaMax" runat="server"></asp:DropDownList></td>
                                    <td>
                                        <input id="txtPRICE" type="text" class="numJe" placeholder="销售成本" runat="server" style="width: 80px" /></td>

                                    <td>
                                        <input type="text" placeholder="售价" class="input-xlarge" runat="server" id="txtPRICE2" style="width: 80px" /></td>

                                    <td>
                                        <input id="txtStart" runat="server" type="text" placeholder="起始时间" readonly class="Wdate" style="width:100px;" />~ <input id="txtEnd" runat="server" type="text" placeholder="截止时间" readonly class="Wdate"  style="width:100px;" /></td>
                                  
                                    <td>
                                        <asp:Button ID="btnAdd" runat="server" Text="新增" CssClass="btn btn-primary btn-xs btn_w60" OnClick="btnAdd_Click" OnClientClick="return checkInput();" /></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </ContentTemplate>
        </asp:UpdatePanel>
        <asp:Literal ID="ltlMatType" Visible="false" runat="server"></asp:Literal>
        <asp:Literal ID="ltlC_EMP_ID" Visible="false" runat="server"></asp:Literal>
        <asp:Literal ID="ltlC_EMP_NAME" Visible="false" runat="server"></asp:Literal>
        <script src="../Assets/js/common.js"></script>
        <script type="text/javascript">
            selectAll("input.qx1", "input.che1");

            function checkInput() {

                if ($.trim($("#txtPRICE").val()) == '') {

                    alert("销售成本不能为空");
                    return false;
                }
               

                return true;
            }
        </script>
    </form>
</body>
</html>
