<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Activity.aspx.cs" Inherits="CRM.BasicData.Activity" %>

<%@ Register Src="~/BasicData/common.ascx" TagPrefix="uc1" TagName="common" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>钢种成本维护</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <uc1:common runat="server" id="common" />
    <script src="JsDate.js"></script>

</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
         <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
        <div class="dv_btn">
            <ul>

                <li runat="server" id="DC">
                    <asp:Button ID="btnSave" runat="server" Text="保 存" CssClass="btn btn-warning btn-xs" OnClick="btnSave_Click" /></li>
                <li runat="server" id="DB">
                    <asp:Button ID="btnDel" runat="server" Text="删除" CssClass="btn btn-warning btn-xs" OnClientClick="return confirm('是否对选中项进行操作?')" OnClick="btnDel_Click" /></li>
                 <li>
                    <button type="button" class="btn btn-warning btn-xs" onclick="return openWeb(6);" runat="server" id="Button1">钢坯</button></li>
                <li runat="server" id="DA">
                    <button type="button" class="btn btn-warning btn-xs" onclick="return openWeb(8);" runat="server" id="btnAdd">线材</button></li>
            </ul>
        </div>
       


                <table style="width: 100%">
                    <tr>
                        <td style="vertical-align: top;">

                            <div style="overflow: auto; height:650px; width: 250px; border: solid 1px #ccc">
                                <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%"
                                    ShowLines="True" AutoGenerateDataBindings="False" OnSelectedNodeChanged="trv_menu_SelectedNodeChanged" ImageSet="XPFileExplorer">
                                    <ParentNodeStyle Font-Bold="False" />
                                    <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
                                    <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                                    <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                                        NodeSpacing="0px" VerticalPadding="0px" />
                                </asp:TreeView>
                            </div>

                        </td>
                        <td style="vertical-align: top">

                            <table class="table table-bordered table-condensed">
                                <tr>
                                    <td>
                                        <asp:DropDownList ID="dropArea" runat="server">
                                        </asp:DropDownList></td>
                                    <td>
                                        <input type="text" placeholder="物料编码" class="input-xlarge" runat="server" id="txtCode" /></td>
                                    <td>
                                        <input type="text" placeholder="钢种" class="input-xlarge" runat="server" id="txt_GRD" /></td>
                                    <td>
                                        <input type="text" placeholder="规格" class="input-xlarge" runat="server" id="txtSPEC" /></td>
                                    <td>日期</td>
                                    <td>
                                        <input id="Start" runat="server" type="text" style="width: 100px;" readonly class="Wdate"  />~
                                <input id="End" runat="server" type="text" style="width: 100px;" readonly class="Wdate"  /></td>

                                    <td>
                                        <asp:Button ID="btnSearch" runat="server" Text="查询" CssClass="btn btn-primary btn-xs btn_w60" OnClick="btnSearch_Click" />
                                    </td>
                                </tr>
                            </table>
                            <div>
                                <span class="red">分类：<asp:Literal ID="ltlC_PROD_NAME"  runat="server"></asp:Literal>
                                     <asp:Literal ID="ltlgroupCode" Visible="false" runat="server"></asp:Literal>
                                </span>
                            </div>
                            <div style="overflow-y: auto;" id="div2">
                                <table class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th style="width: 30px;">
                                                <input id="chxAll" type="checkbox" class="qx1" /></th>
                                            <th>区域</th>
                                            <th>物料编码</th>
                                            <th>钢种</th>
                                            <th>规格</th>
                                            <th>销售成本</th>
                                            <th>售价</th>
                                            <th>起始时间</th>
                                            <th>截止时间</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <asp:Repeater ID="rptList" runat="server">
                                            <ItemTemplate>
                                                <tr>
                                                    <td style="width: 30px;">
                                                        <input id="chkSelect" class="che1" runat="server" type="checkbox" value='<%#DataBinder.Eval (Container.DataItem,"C_ID") %>' /></td>
                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"C_AREAMAX") %></td>

                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"C_MAT_CODE") %>
                                                    </td>
                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"C_STL_GRD") %></td>
                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"C_SPEC") %></td>

                                                    <td>
                                                        <input id="txtPRICE" type="text" class="numJe" value='<%#DataBinder.Eval (Container.DataItem,"N_PRICE") %>' runat="server" style="width: 50px;" /></td>
                                                    <td>
                                                        <input id="txtPRICE2" type="text" class="numJe" runat="server" style="width: 50px;" value='<%#DataBinder.Eval (Container.DataItem,"N_PRICE2") %>' /></td>

                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"D_START_DT","{0:yyy-MM-dd}") %>   
                                                    </td>
                                                    <td>
                                                        <%#DataBinder.Eval (Container.DataItem,"D_END_DT","{0:yyy-MM-dd}") %>
                                                    </td>

                                                </tr>
                                            </ItemTemplate>
                                        </asp:Repeater>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                </table>
            </ContentTemplate>
        </asp:UpdatePanel>

        <asp:Literal ID="ltlC_EMP_ID" Visible="false" runat="server"></asp:Literal>
        <asp:Literal ID="ltlC_EMP_NAME" Visible="false" runat="server"></asp:Literal>

        <script src="../Assets/js/common.js"></script>
        <script type="text/javascript">
            //全选
            selectAll("input.qx1", "input.che1");
            function openWeb(type) {

                var _w =1000;//$(window).width();
                var _h = 580;//$(window).height();
                openPage("ActivityAdd.aspx?type=" + type, _w, _h);
            }
        </script>
    </form>
</body>
</html>
