<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Area.aspx.cs" Inherits="CRM.BasicData.Area" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="../Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../Assets/css/common.css" rel="stylesheet" />
    <title>地理区域</title>
   
</head>
<body>
    <form id="form1" runat="server">

        <table style="width: 100%;">
            <tr>
                <td style="width: 200px; vertical-align: top; border: solid 1px #cccccc">
                    <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%"
                        OnSelectedNodeChanged="trv_menu_SelectedNodeChanged" ShowLines="True" AutoGenerateDataBindings="False">
                        <ParentNodeStyle Font-Bold="False" />
                        <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
                        <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                        <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                            NodeSpacing="0px" VerticalPadding="0px" />
                    </asp:TreeView>
                </td>
                <td style="vertical-align: top; padding-left:10px;">
                    <table class="table table-bordered">
                        <tr>
                            <td style="width: 100px; text-align:right">本级栏目名称</td>
                            <td>
                                <asp:Label ID="lbl_nodeText" runat="server"></asp:Label>&nbsp;&nbsp;
                                                        <asp:Button ID="btnInit" runat="server" Text="初始化根目录" class="btn btn-primary btn-xs" OnClick="btnInit_Click" />
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:right">子栏目
                            </td>
                            <td>
                                <div class="dv_from">
                                    <ul>
                                        <li>编码</li>
                                        <li><asp:TextBox ID="txtCode" runat="server" Font-Size="12px"></asp:TextBox></li>
                                        <li>名称</li>
                                        <li><asp:TextBox ID="txt_menu" runat="server" Font-Size="12px"></asp:TextBox></li>
                                        <li><asp:Button ID="btn_Add" runat="server" Font-Size="12px" OnClick="btn_Add_Click"
                                                Text="添加" class="btn btn-primary btn-xs btn_w60" Width="71px" /></li>
                                    </ul>

                                </div>
                            </td>
                        </tr>
                    </table>
                    <asp:GridView ID="grd_menu" runat="server" AutoGenerateColumns="False" CellPadding="3"
                        DataKeyNames="ID" Font-Size="12px" Width="100%" BorderWidth="1px" OnRowCancelingEdit="grd_menu_RowCancelingEdit"
                        OnRowDeleting="grd_menu_RowDeleting" OnRowDataBound="grd_menu_RowDataBound" OnRowUpdating="grd_menu_RowUpdating"
                        OnRowEditing="grd_menu_RowEditing" CssClass="table table-bordered table-hover">
                        <Columns>
                            <asp:BoundField DataField="C_ID" HeaderText="ID" ReadOnly="True" Visible="False" />
                            <asp:BoundField DataField="N_SORT" HeaderText="排序">
                                <HeaderStyle Width="50px" />
                                <ItemStyle HorizontalAlign="Center" />
                            </asp:BoundField>

                            <asp:BoundField DataField="C_Code" HeaderText="编码">
                                <HeaderStyle HorizontalAlign="Left" />
                                <ItemStyle HorizontalAlign="Left" />
                            </asp:BoundField>
                            <asp:BoundField DataField="C_NAME" HeaderText="名称">
                                <HeaderStyle HorizontalAlign="Left" />
                                <ItemStyle HorizontalAlign="Left" />
                            </asp:BoundField>

                            <asp:CommandField HeaderText="编辑" ShowEditButton="True">
                                <ControlStyle CssClass="linkblue" />
                                <HeaderStyle HorizontalAlign="Center" />
                                <ItemStyle HorizontalAlign="Center" />
                            </asp:CommandField>
                            <asp:CommandField HeaderText="删除" ShowDeleteButton="True">
                                <ControlStyle CssClass="linkblue" />
                                <ItemStyle HorizontalAlign="Center" />
                            </asp:CommandField>
                        </Columns>
                    </asp:GridView>

                </td>
            </tr>
        </table>
        <asp:Label ID="lpx" runat="server" Visible="False">0</asp:Label>
        <asp:Label ID="lgenid" runat="server" Visible="False">-1</asp:Label>
        <asp:Label ID="ldeph" runat="server" Visible="False">0</asp:Label>
        <asp:Label ID="lfid" runat="server" Visible="False">-1</asp:Label>

    </form>
</body>
</html>
