<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Question_Dept.aspx.cs" Inherits="CRM.BasicData.Question_Dept" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="../Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../Assets/css/common.css" rel="stylesheet" />

    <title>技术处理部门</title>
</head>
<body>
    <form id="form1" runat="server">
        <div class="panel panel-default">
            <div class="panel-heading">
                <asp:Button ID="btnSave" runat="server" Text="保 存" CssClass="btn btn-primary btn-xs btn_w60" OnClick="btnSave_Click" /></div>
            <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%" ShowLines="True" AutoGenerateDataBindings="False">
                <ParentNodeStyle Font-Bold="False" />
                <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
                <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                    NodeSpacing="0px" VerticalPadding="0px" />
            </asp:TreeView>
        </div>
        <asp:Literal ID="ltlID" Visible="false" runat="server"></asp:Literal>
         <asp:Literal ID="ltlEmpID" Visible="false" runat="server"></asp:Literal>
         <asp:Literal ID="ltlEmpName" Visible="false" runat="server"></asp:Literal>
    </form>
</body>
</html>
