<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="addrAdd2.aspx.cs" Inherits="CRM.WebForms.Train.addrAdd2" %>

<%@ Register Src="~/WebForms/Train/rollControl.ascx" TagPrefix="uc1" TagName="rollControl" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>到货地点费用添加</title>
    <uc1:rollControl runat="server" ID="rollControl" />
    <script type="text/javascript">
        $(function () {

            $("#txtStart").datetimepicker({
                format: 'yyyy-mm-dd',
                minView: 'month',
                language: 'zh-CN',
                autoclose: true

            });
             $("#txtEnd").datetimepicker({
                format: 'yyyy-mm-dd',
                minView: 'month',
                language: 'zh-CN',
                autoclose: true

            })

        });
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <table style="width: 100%">
            <tr>
                <td style="width: 200px; vertical-align: top">
                    <div style="overflow: auto; max-height: 400px; border: solid 1px #cccccc">

                        <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%" ShowLines="True" ShowCheckBoxes="Leaf" AutoGenerateDataBindings="False">
                            <ParentNodeStyle Font-Bold="False" />
                            <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
                            <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                            <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                                NodeSpacing="0px" VerticalPadding="0px" />
                        </asp:TreeView>
                    </div>
                </td>
                <td style="vertical-align: top">
                    <table class="table table-bordered table-condensed">
                         <tr>
                            <td style="width: 100px;">生效日期</td>
                            <td><input id="txtStart" type="text" style="width: 120px;" readonly="readonly" class="form-control Wdate" runat="server" /></td>
                        </tr>
                        <tr>
                            <td>失效日期</td>
                            <td><input id="txtEnd" type="text" style="width: 120px;" readonly="readonly" class="form-control Wdate" runat="server" /></td>
                        </tr>
                        <tr>
                            <td >承运商</td>
                            <td><asp:DropDownList ID="dropcys" runat="server" Width="200"></asp:DropDownList></td>
                        </tr>
                        <tr>
                            <td>发运方式</td>
                            <td><asp:DropDownList ID="dropfyfs" runat="server" Width="200"></asp:DropDownList></td>
                        </tr>
                        <tr>
                            <td >费用</td>
                            <td>
                                <asp:TextBox ID="txtprice" runat="server" CssClass="numJe"></asp:TextBox></td>
                        </tr>
                       
                        <tr>
                            <td style="width: 100px;">&nbsp;</td>
                            <td>
                                <asp:Button ID="btnadd" CssClass="btn btn-primary btn-xs" runat="server" Text="保存" OnClick="btnadd_Click" />
                            </td>
                        </tr>
                    </table>

                </td>
            </tr>
        </table>
    </form>
</body>
</html>
