<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="_Dept_EMP.aspx.cs" Inherits="CRM.Common._Dept_EMP" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="../Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../Assets/css/common.css" rel="stylesheet" />
    <title>业务员</title>
</head>
<body>
    <form id="form1" runat="server">
        <table style="width: 100%;">
            <tr>
                <td style="vertical-align: top">
                    <div class="panel panel-default">
                        <div class="panel-heading">部门</div>
                        <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%"
                            OnSelectedNodeChanged="trv_menu_SelectedNodeChanged" ShowLines="True" AutoGenerateDataBindings="False">
                            <ParentNodeStyle Font-Bold="False" />
                            <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
                            <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                            <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                                NodeSpacing="0px" VerticalPadding="0px" />
                        </asp:TreeView>
                    </div>
                </td>
                <td style="width: 20px;">&nbsp;</td>
                <td style="vertical-align: top">
                    <div class="panel panel-default">
                        <div class="panel-heading">业务员</div>
                        <table class="table table-bordered table-hover">
                            <tbody>
                                <asp:Repeater ID="rptList" runat="server">
                                    <ItemTemplate>
                                        <tr>
                                            <td><a href="#" onclick="GetEmp('<%#DataBinder.Eval (Container.DataItem,"C_NAME")%>','<%#DataBinder.Eval (Container.DataItem,"c_id")%>');"><%#DataBinder.Eval (Container.DataItem,"C_NAME")%></a></td>
                                        </tr>
                                    </ItemTemplate>
                                </asp:Repeater>

                            </tbody>

                        </table>
                    </div>

                </td>
            </tr>
        </table>

        <script src="../Assets/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript">

            function GetEmp(name, id) {
                window.parent.SetEmp(name, id);
            }

        </script>
    </form>
</body>
</html>
