<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="_MatGroup.aspx.cs" Inherits="CRM.Common._MatGroup" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>物料组</title>
    <link href="../Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../Assets/css/common.css" rel="stylesheet" />
    <script src="../Assets/js/jquery-2.0.3.min.js"></script>
    <script type="text/javascript">
        function GetMat(str) {
            window.parent.SetMatClass(str);
           
        }
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <asp:TreeView ID="trv_menu" runat="server" Font-Bold="False" Font-Size="12px" Width="100%"
            ShowLines="True" AutoGenerateDataBindings="False" ImageSet="XPFileExplorer" OnTreeNodeExpanded="trv_menu_TreeNodeExpanded" OnSelectedNodeChanged="trv_menu_SelectedNodeChanged">
            <ParentNodeStyle Font-Bold="False" />
            <HoverNodeStyle Font-Underline="True" ForeColor="Purple" />
            <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
            <NodeStyle Font-Names="Tahoma" Font-Size="9pt" ForeColor="DarkBlue" HorizontalPadding="5px"
                NodeSpacing="0px" VerticalPadding="0px" />
        </asp:TreeView>
    </form>
</body>
</html>
