//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPLAN_TAPPING
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string PLANID { get; set; }
        public string CONTRACTID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PLANDEPT { get; set; }
        public string EXECUTEDEPT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> PLANEXECUTEDATE { get; set; }
        public Nullable<System.DateTime> ACTUALEXECUTEDATE { get; set; }
        public string PLANNER { get; set; }
        public string PRE_LOTNO { get; set; }
        public string PREHEATID { get; set; }
        public string PRE_STEELGRADEINDEX { get; set; }
        public string PRE_STEELGRADE { get; set; }
        public Nullable<decimal> AIM_TAPPED_WEIGHT { get; set; }
        public string CASTERID { get; set; }
        public string BOFID { get; set; }
        public string LFID { get; set; }
        public string RHID { get; set; }
        public string BOF_STATUS { get; set; }
        public string LF_STATUS { get; set; }
        public string RH_STATUS { get; set; }
        public string CASTER_STATUS { get; set; }
        public string SIDE_STATUS { get; set; }
        public string HEATID { get; set; }
        public string CASTING_NO { get; set; }
        public Nullable<int> CASTING_HEAT_CNT { get; set; }
        public Nullable<System.DateTime> AIM_TIME_IRONPREPARED { get; set; }
        public Nullable<System.DateTime> AIM_TIME_BOFSTART { get; set; }
        public Nullable<System.DateTime> AIM_TIME_BOFTAPPED { get; set; }
        public Nullable<System.DateTime> AIM_TIME_TAPPEDSIDEEND { get; set; }
        public Nullable<System.DateTime> AIM_TIME_LFARRIVAL { get; set; }
        public Nullable<System.DateTime> AIM_TIME_LFSTART { get; set; }
        public Nullable<System.DateTime> AIM_TIME_LFEND { get; set; }
        public Nullable<System.DateTime> AIM_TIME_LFLEAVE { get; set; }
        public Nullable<System.DateTime> AIM_TIME_RHARRIVAL { get; set; }
        public Nullable<System.DateTime> AIM_TIME_RHSTART { get; set; }
        public Nullable<System.DateTime> AIM_TIME_RHEND { get; set; }
        public Nullable<System.DateTime> AIM_TIME_RHLEAVE { get; set; }
        public Nullable<System.DateTime> AIM_TIME_CASTERARRIVAL { get; set; }
        public Nullable<System.DateTime> AIM_TIME_CASTINGSTART { get; set; }
        public Nullable<System.DateTime> AIM_TIME_CASTINGEND { get; set; }
        public Nullable<int> FIR_HEAT_FLAG { get; set; }
        public string DIV_HEATID { get; set; }
        public string TEAMID { get; set; }
        public string SHIFTID { get; set; }
        public string STEELGRADEINDEX { get; set; }
        public string STEELGRADE { get; set; }
        public string PLAN_ORD_ID { get; set; }
        public Nullable<int> HOT_SEND_FLAG { get; set; }
        public Nullable<int> STEEL_RETURN_FLAG { get; set; }
        public Nullable<int> STEEL_BACK_FLAG { get; set; }
        public string TREAT_SEQ { get; set; }
        public string DESTITATION { get; set; }
        public Nullable<short> NEW_BOF_FLAG { get; set; }
        public string REFINE_TYPE { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> THICKNESS { get; set; }
        public string AODID { get; set; }
        public string DEPID { get; set; }
        public string RHLID { get; set; }
        public string DEP_STATUS { get; set; }
        public string RHL_STATUS { get; set; }
        public string AOD_STATUS { get; set; }
    }
}
