//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITEM_TYPE
    {
        public string C_ID { get; set; }
        public string C_TYPE { get; set; }
        public string C_ITEM_CODE { get; set; }
        public string C_ITEM_NAME { get; set; }
        public short N_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<System.DateTime> D_END_DATE { get; set; }
        public Nullable<short> N_SORT { get; set; }
    }
}
