//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LG_PLAN_EDIT_LOG
    {
        public string C_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_ORDER_ID_BEFORE { get; set; }
        public string C_STL_GRD_BEFORE { get; set; }
        public string C_STD_CODE_BEFORE { get; set; }
        public string C_SLAB_SIZE_BEFORE { get; set; }
        public string C_LENGTH_BEFORE { get; set; }
        public string C_MAT_CODE_BEFORE { get; set; }
        public string C_ZL_DESC_BEFORE { get; set; }
        public string C_LF_DESC_BEFORE { get; set; }
        public string C_RH_DESC_BEFORE { get; set; }
        public string C_CC_DESC_BEFORE { get; set; }
        public string C_ORDER_ID_AFTER { get; set; }
        public string C_STL_GRD_AFTER { get; set; }
        public string C_STD_CODE_AFTER { get; set; }
        public string C_SLAB_SIZE_AFTER { get; set; }
        public string C_LENGTH_AFTER { get; set; }
        public string C_MAT_CODE_AFTER { get; set; }
        public string C_ZL_DESC_AFTER { get; set; }
        public string C_LF_DESC_AFTER { get; set; }
        public string C_RH_DESC_AFTER { get; set; }
        public string C_CC_DESC_AFTER { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_REASON { get; set; }
    }
}
