//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MATRL_CONTRAST
    {
        public string C_ID { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public Nullable<decimal> N_SLAB_LENTH { get; set; }
        public string C_KP_SIZE { get; set; }
        public Nullable<decimal> N_KP_LENTH { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_REMARK1 { get; set; }
        public string C_REMARK2 { get; set; }
        public string C_REMARK3 { get; set; }
    }
}
