//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MATRL_GROUP
    {
        public string C_ID { get; set; }
        public string C_MAT_GROUP_CODE { get; set; }
        public string C_MAT_GROUP_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_MAT_TYPE { get; set; }
        public string C_CLS_TYPE { get; set; }
        public string C_REMARK1 { get; set; }
        public string C_REMARK2 { get; set; }
        public string C_REMARK3 { get; set; }
        public Nullable<short> N_LEV { get; set; }
    }
}
