//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MATRL_MAIN
    {
        public string C_ID { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_MAT_GROUP_CODE { get; set; }
        public string C_MAT_GROUP_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public Nullable<decimal> N_THK { get; set; }
        public Nullable<decimal> N_WTH { get; set; }
        public Nullable<decimal> N_LTH { get; set; }
        public string C_MAT_TYPE { get; set; }
        public string C_CLS_TYPE { get; set; }
        public string C_REMARK1 { get; set; }
        public string C_REMARK2 { get; set; }
        public string C_REMARK3 { get; set; }
        public string C_NC_PK { get; set; }
        public string C_PK_INVCL { get; set; }
        public string C_PK_INVBASDOC { get; set; }
        public string C_PK_INVMANDOC { get; set; }
        public string C_PK_PRODUCE { get; set; }
        public string C_PK_MEASDOC { get; set; }
        public string C_PK_TAXITEMS { get; set; }
        public string C_INVSHORTNAME { get; set; }
        public short N_ISGPS { get; set; }
        public short C_IS_VISIBLE { get; set; }
        public string C_FJLDW { get; set; }
        public Nullable<decimal> N_HSL { get; set; }
        public string C_ZJLDWMC { get; set; }
        public string C_FJLDWMC { get; set; }
        public string C_PLANEMP { get; set; }
        public string C_PK_PSID { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public string C_YT { get; set; }
    }
}
