//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REHEATING_FURNACE
    {
        public string C_ID { get; set; }
        public string C_TYPE { get; set; }
        public Nullable<decimal> N_HOUR { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_ZL_TYPE { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_BY1 { get; set; }
        public string C_BY2 { get; set; }
        public string C_BY3 { get; set; }
        public string C_BY4 { get; set; }
        public string C_BY5 { get; set; }
        public string C_BY6 { get; set; }
    }
}
