//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCS_CS
    {
        public string C_ID { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SPEC1 { get; set; }
        public string C_TIME { get; set; }
        public string C_STA_ID { get; set; }
        public string C_SPEC2 { get; set; }
        public string C_WD { get; set; }
    }
}
