//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TI_DDFP_LOG
    {
        public string C_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public string C_BL1 { get; set; }
        public string C_BL2 { get; set; }
        public Nullable<decimal> N_WGT1 { get; set; }
        public Nullable<decimal> N_WGT2 { get; set; }
        public string C_BATCH_NO { get; set; }
        public Nullable<decimal> N_NUM { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_BARCODE { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public Nullable<decimal> N_DDWGT { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_AREA { get; set; }
        public string C_REMARK { get; set; }
    }
}
