//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_NCADDRESS_COST_LOG
    {
        public string C_ID { get; set; }
        public string C_CHENGYUN { get; set; }
        public string C_FAYUN { get; set; }
        public string C_ADDRCODE { get; set; }
        public string C_ADDRNAME { get; set; }
        public Nullable<decimal> N_PRICE { get; set; }
        public Nullable<System.DateTime> D_START_DT { get; set; }
        public Nullable<System.DateTime> D_END_DT { get; set; }
        public string C_CREATE_EMP { get; set; }
        public Nullable<System.DateTime> D_CREATE_DT { get; set; }
        public string C_ADDR_NCPK { get; set; }
        public string C_AREA_PK { get; set; }
        public string N_STATUS { get; set; }
        public string C_EMP { get; set; }
        public Nullable<System.DateTime> D_EMP { get; set; }
    }
}
