//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_PROC
    {
        public string C_ID { get; set; }
        public string C_STLGRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_STDCODE { get; set; }
        public string C_DESC { get; set; }
        public string C_REMARK { get; set; }
        public string C_PROCTYPE { get; set; }
        public string C_IMGURL { get; set; }
        public Nullable<System.DateTime> D_DATE { get; set; }
        public Nullable<decimal> N_SORT { get; set; }
        public Nullable<decimal> N_STATUS { get; set; }
    }
}
