//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_ACTIVITY
    {
        public string C_ID { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<decimal> N_PRICE { get; set; }
        public Nullable<decimal> N_PRICE2 { get; set; }
        public short C_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_AREAMAX { get; set; }
        public string C_PROD_NAME { get; set; }
        public Nullable<System.DateTime> D_START_DT { get; set; }
        public Nullable<System.DateTime> D_END_DT { get; set; }
    }
}
