//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_XG
    {
        public string C_ID { get; set; }
        public string C_NAME { get; set; }
        public string C_FR { get; set; }
        public string C_WT { get; set; }
        public string C_JB { get; set; }
        public string C_TEL { get; set; }
        public string C_FAX { get; set; }
        public string C_BANK_NAME { get; set; }
        public string C_BANK_NO { get; set; }
        public string C_REMARK { get; set; }
        public string C_EXTEND1 { get; set; }
        public string C_EXTEND2 { get; set; }
        public string C_EXTEND3 { get; set; }
        public string C_EXTEND4 { get; set; }
    }
}
