//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_STLGRD_PRICE_WGT
    {
        public string C_ID { get; set; }
        public Nullable<System.DateTime> D_MONTH { get; set; }
        public string C_MAT_GROUP_CODE { get; set; }
        public string C_MAT_GROUP_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_SPEC_MIN { get; set; }
        public string C_SPEC_MAX { get; set; }
        public string C_PRICE { get; set; }
        public string C_MAOLI { get; set; }
        public string C_COST { get; set; }
        public string C_BJGX { get; set; }
        public string C_FIX_COST { get; set; }
        public string C_SALESORG { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public string C_EMPID { get; set; }
        public string C_EMPNAME { get; set; }
    }
}
