//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_NOTICE
    {
        public string C_ID { get; set; }
        public string C_CLASS { get; set; }
        public string C_TITLE { get; set; }
        public string C_PICURL { get; set; }
        public string C_LINK { get; set; }
        public string C_CONTENT { get; set; }
        public string C_FILE { get; set; }
        public short N_SORT { get; set; }
        public string C_REMARK { get; set; }
        public short N_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
