//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMB_NCADDRESS
    {
        public string C_ID { get; set; }
        public string ADDRCODE { get; set; }
        public string ADDRNAME { get; set; }
        public string PK_ADDRESS { get; set; }
        public string PK_AREACL { get; set; }
        public string PK_CORP { get; set; }
        public string POSTALCODE { get; set; }
        public string PROVINCE { get; set; }
    }
}
