//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_TRAIN_MAIN
    {
        public string C_ID { get; set; }
        public string C_EMPID { get; set; }
        public string C_EMPNAME { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public string C_STATION { get; set; }
        public string C_PLANNO { get; set; }
        public string C_LINE { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<System.DateTime> D_EDIT_DT { get; set; }
        public Nullable<decimal> N_TRAIN_NUM { get; set; }
        public string C_SHIPVIA { get; set; }
        public string C_ISCHECK { get; set; }
        public string C_CHECKEMP { get; set; }
        public Nullable<System.DateTime> D_CHECKTIME { get; set; }
    }
}
