//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_TRAIN
    {
        public string C_ID { get; set; }
        public string C_EMPNAME { get; set; }
        public Nullable<System.DateTime> D_DATE { get; set; }
        public string C_FLAG { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<long> N_TRAIN_NUM { get; set; }
        public string C_STATION { get; set; }
        public string C_STATION_J { get; set; }
        public string C_PLANNO { get; set; }
        public string C_CUSTNO { get; set; }
        public string C_CUSTNAME { get; set; }
        public string C_AREA { get; set; }
        public Nullable<System.DateTime> D_MONTH { get; set; }
        public string C_TYPE { get; set; }
    }
}
