//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_CUST_BOOK
    {
        public string C_ID { get; set; }
        public Nullable<System.DateTime> D_ZF_DT { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_AREA { get; set; }
        public string C_CUST_MANAGE { get; set; }
        public string C_CUST_EMP { get; set; }
        public string C_CUST_EMP_TEL { get; set; }
        public string C_MEETING_CUST { get; set; }
        public string C_MEETING_XG { get; set; }
        public string C_MAIN_CONTENT { get; set; }
        public string C_NEED_S_Q { get; set; }
        public string C_LEAVE_Q { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_PRO_USE { get; set; }
        public string C_SITE { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_EMPID { get; set; }
    }
}
