//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_CUSTGMARK_MAIN
    {
        public string C_ID { get; set; }
        public string C_TITLE { get; set; }
        public string C_XGID { get; set; }
        public string C_STLGRD { get; set; }
        public Nullable<System.DateTime> D_TIME { get; set; }
        public string C_CUSTNO { get; set; }
        public string C_CUSTNAME { get; set; }
        public string C_EMPID { get; set; }
        public string C_EMPNAME { get; set; }
        public Nullable<decimal> N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_ORDER_NO { get; set; }
    }
}
