//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_ROLL_DEPLOY_LOG
    {
        public string C_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_OLDAREA { get; set; }
        public string C_NEWAREA { get; set; }
        public string C_EMPID { get; set; }
        public string C_EMPNAME { get; set; }
        public Nullable<System.DateTime> D_MOD { get; set; }
        public string C_ROLL_PROCID { get; set; }
        public string C_QUA { get; set; }
        public string C_REMARK { get; set; }
        public string C_PACK { get; set; }
        public string C_JUDGE_LEV { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_OLDCUST { get; set; }
        public string C_NEWCUST { get; set; }
        public string C_OLDCON { get; set; }
        public string C_NEWCON { get; set; }
        public string C_ORDERNO { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
    }
}
