//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_TECH_CONSULT
    {
        public string C_ID { get; set; }
        public string C_QUEST_ID { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_CUST_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_USE_DESC { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_DEPT { get; set; }
        public string C_EMP { get; set; }
        public Nullable<System.DateTime> D_PLAN_DT { get; set; }
        public Nullable<System.DateTime> D_FINISH_DT { get; set; }
        public string C_REAL_TIME { get; set; }
        public string C_RESULT { get; set; }
        public string C_LEAVE_Q { get; set; }
        public string C_REMARK2 { get; set; }
        public Nullable<long> N_CUST_EVAL { get; set; }
        public short N_STATE { get; set; }
        public Nullable<System.DateTime> D_CUST_EVAL_DT { get; set; }
        public Nullable<short> N_XG_EVAL { get; set; }
        public string C_XG_EVAL_EMP { get; set; }
        public Nullable<System.DateTime> D_XG_EVAL_DT { get; set; }
        public string C_ORDER_NO { get; set; }
    }
}
