//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC_TRAIN_EXPORT_LOG
    {
        public string C_ID { get; set; }
        public string C_PLANNO { get; set; }
        public string C_CODE { get; set; }
        public string C_EMPNAME { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public string C_DH_COMPANY { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<decimal> N_TRAIN_NUM { get; set; }
        public string C_STATION { get; set; }
    }
}
