//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_GPFY_LOG
    {
        public string C_ID { get; set; }
        public string C_FYDH { get; set; }
        public string C_TYPE { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<short> N_NUM { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_SEND_STOCK { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SPEC { get; set; }
        public string C_ZLDJ { get; set; }
        public string C_BZYQ { get; set; }
        public string C_LIC_PLA_NO { get; set; }
    }
}
