//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_DELIVERY_ORDER
    {
        public string C_ID { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_GPS_NO { get; set; }
        public string C_NO { get; set; }
        public string C_CON_NO { get; set; }
        public Nullable<System.DateTime> D_DISP_DT { get; set; }
        public string C_SHIPVIA { get; set; }
        public string C_COMCAR { get; set; }
        public string C_PATH { get; set; }
        public string C_PATH_DESC { get; set; }
        public string C_SEND_DEPT { get; set; }
        public string C_BUSINESS_DEPT { get; set; }
        public string C_BUSINESS_ID { get; set; }
        public Nullable<short> N_IS_WIRESALE { get; set; }
        public Nullable<short> N_IS_EXPORT { get; set; }
        public string C_LIC_PLA_NO { get; set; }
        public string C_ATSTATION { get; set; }
        public Nullable<System.DateTime> D_APPROVE_DT { get; set; }
        public Nullable<System.DateTime> D_CREATE_DT { get; set; }
        public string C_APPROVE_ID { get; set; }
        public string C_CREATE_ID { get; set; }
        public string C_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
    }
}
