//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_DISPATCH_TMZJB
    {
        public string C_ID { get; set; }
        public string C_DISPATCH_ID { get; set; }
        public string C_SEND_STOCK { get; set; }
        public string C_NO { get; set; }
        public string C_SHIPVIA { get; set; }
        public string C_LIC_PLA_NO { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_JUDGE_LEV_ZH { get; set; }
        public Nullable<decimal> N_NUM { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_Z_DW { get; set; }
        public string C_F_DW { get; set; }
        public string C_ATSTATION { get; set; }
        public string C_BUSINESS_DEPT { get; set; }
        public string C_BUSINESS_ID { get; set; }
        public string C_CREATE_ID { get; set; }
        public Nullable<System.DateTime> D_CREATE_DT { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_ZYX1 { get; set; }
        public string C_ZYX2 { get; set; }
        public string C_BZYQ { get; set; }
        public string C_ZYX4 { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_AREA { get; set; }
        public string C_CKDH { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<decimal> N_JZWGT { get; set; }
    }
}
