//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_DISPATCHDETAILS_MAIN_LOG
    {
        public string C_ID { get; set; }
        public string C_LOG_ID { get; set; }
        public string C_DISPATCH_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_TICK_NO { get; set; }
        public string C_SLAB_NO { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SEND_STOCK { get; set; }
        public string C_QUALIRY_LEV { get; set; }
        public string C_FREE_TERM { get; set; }
        public string C_ELSENEED { get; set; }
        public Nullable<decimal> N_COM_AMOUNT_WGT { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_EQUATION_FACTOR { get; set; }
        public Nullable<int> N_OUT_STOCK_WGT { get; set; }
        public string C_UNITIS { get; set; }
        public string C_SEND_SITE { get; set; }
        public string C_AOG_SITE { get; set; }
        public string C_ORGO_CUST { get; set; }
        public string C_CGC { get; set; }
        public Nullable<short> N_IS_SEND_CLOSE { get; set; }
        public string C_ORDER_TYPE { get; set; }
        public string C_SEND_AREA { get; set; }
        public string C_AREA { get; set; }
        public string C_AU_UNITIS { get; set; }
        public string C_CUSTFILE_ID { get; set; }
        public string C_CUST_ID { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<decimal> D_CAL_FAKE_WGT_DT { get; set; }
        public Nullable<decimal> N_CAL_FAKE_WGT { get; set; }
        public Nullable<decimal> N_CAL_PACK_WGT { get; set; }
        public Nullable<decimal> N_CAL_TRUE_WGT { get; set; }
        public Nullable<decimal> N_CAL_FAKE_WGT_DT { get; set; }
        public Nullable<decimal> N_CAL_PACK_WGT_DT { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
