//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_FYZB
    {
        public string C_ID { get; set; }
        public string C_DEPT { get; set; }
        public Nullable<long> N_WGT { get; set; }
        public Nullable<System.DateTime> D_DAY { get; set; }
        public string C_EMPID { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public Nullable<decimal> N_ZKWGT { get; set; }
        public Nullable<decimal> N_JKWGT { get; set; }
        public Nullable<decimal> N_CQWGT { get; set; }
        public Nullable<decimal> N_KCZB { get; set; }
        public Nullable<decimal> N_JKZB { get; set; }
        public Nullable<decimal> N_CQZB { get; set; }
        public Nullable<decimal> N_FYJKZB { get; set; }
        public Nullable<decimal> N_FYCQZB { get; set; }
        public Nullable<decimal> N_QYFY { get; set; }
        public Nullable<decimal> N_QYJKFY { get; set; }
        public Nullable<decimal> N_HYFY { get; set; }
        public Nullable<decimal> N_HYJKFY { get; set; }
        public string C_FLAG { get; set; }
        public Nullable<decimal> N_CQFY { get; set; }
        public Nullable<short> N_SORT { get; set; }
        public Nullable<decimal> N_DPWGT { get; set; }
        public Nullable<decimal> N_MONTH_ZB { get; set; }
        public Nullable<decimal> N_MONTH_JK_ZB { get; set; }
    }
}
