//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_DISPATCH_SJZJB
    {
        public string C_ID { get; set; }
        public string C_DISPATCH_ID { get; set; }
        public Nullable<short> N_NUM { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_CKDH { get; set; }
        public Nullable<decimal> N_JZ { get; set; }
        public string C_SEND_STOCK { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SPEC { get; set; }
        public string C_PK_NCID { get; set; }
        public string C_MZDATE { get; set; }
        public Nullable<decimal> N_MWGT { get; set; }
        public Nullable<decimal> N_PWGT { get; set; }
        public string N_MZTIME { get; set; }
        public string N_PZTIME { get; set; }
        public string C_PZDATE { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<System.DateTime> D_CKSJ { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_TICK_STR { get; set; }
        public string C_ZLDJ { get; set; }
        public string C_BZYQ { get; set; }
        public string C_PRINTEMP { get; set; }
        public Nullable<System.DateTime> D_PRINTTIME { get; set; }
        public Nullable<short> N_PRINT_STATUS { get; set; }
        public Nullable<short> N_PRINT_NUM { get; set; }
        public string C_PDEMP { get; set; }
        public Nullable<System.DateTime> D_PDTIME { get; set; }
        public string C_REMARK { get; set; }
        public string C_PRINTTYPE { get; set; }
    }
}
