//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMD_HY_PLAN
    {
        public string C_ID { get; set; }
        public string C_TITLE { get; set; }
        public Nullable<long> N_PLAN_NUM { get; set; }
        public Nullable<long> N_END_NUM { get; set; }
        public Nullable<long> N_START_NUM { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public Nullable<long> N_ZT_NUM { get; set; }
    }
}
