//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMF_FILEINFO
    {
        public string C_ID { get; set; }
        public string C_FLOW_ID { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_TITLE { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<System.DateTime> D_SB_DT { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public string C_TASK_ID { get; set; }
        public string C_REMARK { get; set; }
        public string C_STEP_ID { get; set; }
        public string C_FILEURL { get; set; }
        public string C_CONTENT { get; set; }
    }
}
