//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_SALEORDER
    {
        public string C_ID { get; set; }
        public string C_CODE { get; set; }
        public string C_CONNO { get; set; }
        public string C_INITIALIZE_ID { get; set; }
        public string C_PK_CORP { get; set; }
        public string C_BIZTYPE { get; set; }
        public Nullable<System.DateTime> D_BILLDATE { get; set; }
        public string C_CUSTOMERID { get; set; }
        public string C_DEPTID { get; set; }
        public string C_EMPLOYEEID { get; set; }
        public string C_OPERATORID { get; set; }
        public string C_COPERATORID { get; set; }
        public string C_SALECORPID { get; set; }
        public string C_CALBODYID { get; set; }
        public string C_RECEIPTCUSTOMERID { get; set; }
        public string C_RECEIVEADDRESS { get; set; }
        public string C_RECEIPTCORPID { get; set; }
        public string C_TRANSMODEID { get; set; }
        public Nullable<System.DateTime> D_MAKEDATE { get; set; }
        public string C_APPROVEID { get; set; }
        public Nullable<System.DateTime> D_APPROVEDATE { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<short> N_STATUS { get; set; }
    }
}
