//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_ORDER_LOG
    {
        public string C_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_TECH_PROT { get; set; }
        public string C_FREE1 { get; set; }
        public string C_FREE2 { get; set; }
        public string C_PACK { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_VDEF1 { get; set; }
        public string C_PRO_USE { get; set; }
        public string C_CUST_SQ { get; set; }
        public string C_FUNITID { get; set; }
        public string C_UNITID { get; set; }
        public Nullable<decimal> N_HSL { get; set; }
        public Nullable<decimal> N_FNUM { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<decimal> N_COST { get; set; }
        public Nullable<decimal> N_TAXRATE { get; set; }
        public Nullable<decimal> N_ORIGINALCURPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXMNY { get; set; }
        public Nullable<decimal> N_ORIGINALCURMNY { get; set; }
        public Nullable<decimal> N_ORIGINALCURSUMMNY { get; set; }
        public Nullable<System.DateTime> D_NEED_DT { get; set; }
        public Nullable<System.DateTime> D_DELIVERY_DT { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public Nullable<short> N_USER_LEV { get; set; }
        public string C_LEV { get; set; }
        public string C_ORDER_LEV { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public string C_BY4 { get; set; }
        public Nullable<System.DateTime> D_LOG_DT { get; set; }
        public string C_RECEIPTAREAID { get; set; }
        public string C_RECEIVEADDRESS { get; set; }
        public string C_RECEIPTCORPID { get; set; }
        public string C_CURRENCYTYPEID { get; set; }
        public string C_TRANSMODE { get; set; }
        public string C_TRANSMODEID { get; set; }
        public string C_YWY { get; set; }
        public string C_SFPJ { get; set; }
        public string C_DESIGN_NO { get; set; }
    }
}
