//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_CONDETAILS
    {
        public string C_NO { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CON_NAME { get; set; }
        public string C_AREA { get; set; }
        public string C_XGID { get; set; }
        public string C_INVBASDOCID { get; set; }
        public string C_INVENTORYID { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_PRO_USE { get; set; }
        public string C_PACKUNITID { get; set; }
        public string C_UNITID { get; set; }
        public string C_CUST_SQ { get; set; }
        public Nullable<System.DateTime> D_NEED_DT { get; set; }
        public Nullable<System.DateTime> D_DELIVERY_DT { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public string C_TECH_PROT { get; set; }
        public string C_FREE_TERM { get; set; }
        public string C_FREE_TERM2 { get; set; }
        public string C_PACK { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_CRECEIPTAREAID { get; set; }
        public string C_ADDRESS { get; set; }
        public string C_RECEIPTCORPID { get; set; }
        public string C_ATSTATION { get; set; }
        public string C_CURRENCYTYPEID { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_DESIGN_NO { get; set; }
        public string C_STDID { get; set; }
        public string C_DESIGNID { get; set; }
        public Nullable<decimal> N_SLAB_MATCH_WGT { get; set; }
        public Nullable<decimal> N_LINE_MATCH_WGT { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<short> N_FLAG { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public Nullable<short> N_EXEC_STATUS { get; set; }
        public Nullable<short> N_USER_LEV { get; set; }
        public string C_EDITEMPLOYEEID { get; set; }
        public Nullable<System.DateTime> D_EDITDATE { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_SALE_CHANNEL { get; set; }
        public string C_LEV { get; set; }
        public string C_ORDER_LEV { get; set; }
        public Nullable<decimal> N_COST { get; set; }
        public Nullable<decimal> N_TAXRATE { get; set; }
        public Nullable<decimal> N_ORIGINALCURPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURNETPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXNETPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXMNY { get; set; }
        public Nullable<decimal> N_ORIGINALCURMNY { get; set; }
        public Nullable<decimal> N_ORIGINALCURSUMMNY { get; set; }
        public Nullable<decimal> N_PRICE { get; set; }
        public Nullable<decimal> N_TAXPRICE { get; set; }
        public Nullable<decimal> N_NETPRICE { get; set; }
        public Nullable<decimal> N_TAXNETPRICE { get; set; }
        public Nullable<decimal> N_TAXMNY { get; set; }
        public Nullable<decimal> N_MNY { get; set; }
        public Nullable<decimal> N_SUMMNY { get; set; }
        public string C_NC_STATE { get; set; }
        public Nullable<decimal> N_FNUM { get; set; }
        public Nullable<decimal> N_HSL { get; set; }
        public string C_VDEF1 { get; set; }
    }
}
