//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_SALEORDERITEM
    {
        public string C_ID { get; set; }
        public string C_BILLID { get; set; }
        public string C_ORDERNO { get; set; }
        public string C_CONNO { get; set; }
        public string C_INVBASDOCID { get; set; }
        public string C_INVENTORYID { get; set; }
        public string C_UNITID { get; set; }
        public string C_FUNITID { get; set; }
        public Nullable<decimal> N_NUMBER { get; set; }
        public Nullable<System.DateTime> D_CONSIGNDATE { get; set; }
        public Nullable<System.DateTime> D_DELIVERDATE { get; set; }
        public string C_PK_CORP { get; set; }
        public string C_ADVISECALBODYID { get; set; }
        public string C_CURRENCYTYPEID { get; set; }
        public Nullable<decimal> N_TAXRATE { get; set; }
        public Nullable<decimal> N_ORIGINALCURPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXPRICE { get; set; }
        public Nullable<decimal> N_ORIGINALCURTAXMNY { get; set; }
        public Nullable<decimal> N_ORIGINALCURMNY { get; set; }
        public string C_RECEIPTAREAID { get; set; }
        public string C_RECEIVEADDRESS { get; set; }
        public string C_RECEIPTCORPID { get; set; }
        public Nullable<decimal> N_ORIGINALCURSUMMNY { get; set; }
        public string C_VFREE1 { get; set; }
        public string C_VFREE2 { get; set; }
        public string C_VFREE3 { get; set; }
        public string C_VDEF1 { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_INITORDERID { get; set; }
        public string C_INITIALIZE_ID { get; set; }
    }
}
