//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_ORDER_PCZB
    {
        public string C_ID { get; set; }
        public string C_AREA { get; set; }
        public Nullable<decimal> N_MONTH_JK_ZB { get; set; }
        public Nullable<decimal> N_MONTH_JP_ZB { get; set; }
        public Nullable<decimal> N_MONTH_PZ_ZB { get; set; }
        public Nullable<decimal> N_DAY_JK_ZB { get; set; }
        public Nullable<decimal> N_DAY_JP_ZB { get; set; }
        public Nullable<decimal> N_DAY_PZ_ZB { get; set; }
        public Nullable<decimal> N_CON_WGT { get; set; }
        public Nullable<System.DateTime> D_PLAN_DT { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public string C_CREATE_ID { get; set; }
        public Nullable<System.DateTime> D_CREATE_DT { get; set; }
        public string C_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_EMP_DT { get; set; }
        public string C_FLAG { get; set; }
        public Nullable<decimal> N_PC_JK { get; set; }
        public Nullable<decimal> N_PC_JP { get; set; }
        public Nullable<decimal> N_PC_PZ { get; set; }
        public Nullable<int> N_SORT { get; set; }
        public Nullable<decimal> N_MONTH_PT_ZB { get; set; }
        public Nullable<decimal> N_DAY_PT_ZB { get; set; }
        public Nullable<decimal> N_PC_PT { get; set; }
    }
}
