//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_LOWMAOLI_ORDER
    {
        public string C_ID { get; set; }
        public string C_CUSTNAME { get; set; }
        public string C_CONNO { get; set; }
        public string C_ORDERNO { get; set; }
        public string C_STLGRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_MAOLI { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_EMPID { get; set; }
        public string C_EMPNAME { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public Nullable<System.DateTime> D_CONSING_DT { get; set; }
        public Nullable<System.DateTime> D_CONEFFE_DT { get; set; }
        public string C_SALEORG { get; set; }
        public Nullable<decimal> N_PRICE { get; set; }
        public Nullable<decimal> N_COSTPRICE { get; set; }
    }
}
