//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMO_CON
    {
        public string C_CON_NO { get; set; }
        public string C_CON_NAME { get; set; }
        public string C_CONTYPEID { get; set; }
        public string C_CUSTOMERID { get; set; }
        public string C_CUSTNAME { get; set; }
        public string C_COPERATORID { get; set; }
        public Nullable<System.DateTime> D_DMAKEDATE { get; set; }
        public string C_CURRENCYTYPEID { get; set; }
        public Nullable<System.DateTime> D_CONSING_DT { get; set; }
        public Nullable<System.DateTime> D_CONEFFE_DT { get; set; }
        public Nullable<System.DateTime> D_CONINVALID_DT { get; set; }
        public string C_TRANSMODEID { get; set; }
        public string C_AREA { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string N_FLAG { get; set; }
        public string C_SALECORPID { get; set; }
        public string C_BIZTYPE { get; set; }
        public string C_DEPTID { get; set; }
        public string C_EMPLOYEEID { get; set; }
        public string C_EDITEMPLOYEEID { get; set; }
        public Nullable<System.DateTime> D_EDITDATE { get; set; }
        public string C_APPROVEID { get; set; }
        public Nullable<System.DateTime> D_APPROVEDATE { get; set; }
        public string C_FLOWID { get; set; }
        public string C_XGID { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public Nullable<short> N_CUST_LEV { get; set; }
        public string C_CRECEIPTCUSTOMERID { get; set; }
        public string C_ADDRESS { get; set; }
        public string C_CRECEIPTAREAID { get; set; }
        public string C_CRECEIPTCORPID { get; set; }
        public string C_STATION { get; set; }
        public string C_REAMRK { get; set; }
        public Nullable<System.DateTime> D_CHANGEDATE { get; set; }
        public Nullable<System.DateTime> D_NEED_DT { get; set; }
        public string C_NC_STATE { get; set; }
        public string C_CHANGEEMPID { get; set; }
        public Nullable<short> N_CHANGENUM { get; set; }
        public string C_RECEIPTCODE { get; set; }
        public Nullable<short> N_OLDSTATUS { get; set; }
        public string C_CON_NO_OLD { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_CON_XH { get; set; }
    }
}
