//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_DAYPLAN
    {
        public string C_ID { get; set; }
        public string C_PLCODE { get; set; }
        public string C_PKBILLB { get; set; }
        public string C_PKBILLH { get; set; }
        public string C_CONNO { get; set; }
        public string C_ORDERNO { get; set; }
        public string C_PKINV { get; set; }
        public string C_PKASSISTMEASURE { get; set; }
        public Nullable<decimal> N_ASSISTNUM { get; set; }
        public Nullable<decimal> N_NUM { get; set; }
        public Nullable<decimal> N_UNITPRICE { get; set; }
        public Nullable<decimal> N_MONEY { get; set; }
        public Nullable<System.DateTime> D_PLANDATE { get; set; }
        public Nullable<System.DateTime> D_ORDSNDATE { get; set; }
        public Nullable<System.DateTime> D_REQUIREDATE { get; set; }
        public Nullable<System.DateTime> D_SNDDATE { get; set; }
        public string C_PKCUST { get; set; }
        public string C_PKSENDTYPE { get; set; }
        public string C_PKSALECORP { get; set; }
        public string C_PKSALEORG { get; set; }
        public string C_PKSENDSTOREORG { get; set; }
        public string C_PKOPERATOR { get; set; }
        public string C_PKOPRDEPART { get; set; }
        public string C_PKPLANPERSON { get; set; }
        public string C_PKAPPRPERSON { get; set; }
        public Nullable<System.DateTime> D_APPRDATE { get; set; }
        public string C_PKARRIVEAREA { get; set; }
        public string C_DESTADDRESS { get; set; }
        public string C_RECEIPTCORPID { get; set; }
        public string C_BIZTYPE { get; set; }
        public string C_REMARK { get; set; }
        public string C_PKSENDAREA { get; set; }
        public string C_PKDELIVORG { get; set; }
        public string C_UNITID { get; set; }
        public string C_VFREE1 { get; set; }
        public string C_VFREE2 { get; set; }
        public string C_VFREE3 { get; set; }
        public string C_VFREE4 { get; set; }
        public string C_SALECODE { get; set; }
        public Nullable<short> N_EXEC_STATUS { get; set; }
        public Nullable<System.DateTime> D_NC_DATE { get; set; }
    }
}
