//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_PLAN
    {
        public string C_ID { get; set; }
        public string C_NO { get; set; }
        public string C_CON_NO { get; set; }
        public Nullable<System.DateTime> D_PLANSEND_DT { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_QUALIRY_LEV { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<decimal> N_SENDNUM_WGT { get; set; }
        public string C_ATSTATION { get; set; }
        public string C_AREA { get; set; }
        public string C_ADDR { get; set; }
        public string C_SHIPVIA { get; set; }
        public string C_CGC { get; set; }
        public string C_ORGO_CUST { get; set; }
        public string C_SEND_STOCK_DEPT { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<System.DateTime> D_ORRE_AOG_DT { get; set; }
        public string C_SEND_STOCK { get; set; }
        public string C_AOG_STOCK_DEPT { get; set; }
        public string C_AOG_STOCK { get; set; }
        public string C_SEND_COM { get; set; }
        public string C_SALE_COM { get; set; }
        public string C_AOG_COM { get; set; }
        public string C_SEND_AREA { get; set; }
        public string C_SEND_ADDR { get; set; }
        public string C_SEND_SITE { get; set; }
        public string C_AOG_SITE { get; set; }
        public Nullable<decimal> N_OUT_STOCK_WGT { get; set; }
        public Nullable<decimal> N_SIGN_WGT { get; set; }
        public Nullable<decimal> N_BACK_WGT { get; set; }
        public Nullable<decimal> N_DAMAGE_WGT { get; set; }
        public Nullable<System.DateTime> D_FOR_PLAN_DT { get; set; }
        public string C_FOR_PALN_ID { get; set; }
        public Nullable<System.DateTime> D_APPROVE_DT { get; set; }
        public string C_APPROVE_ID { get; set; }
        public string C_ORDER_TYPE { get; set; }
        public Nullable<short> N_SORO_BACK { get; set; }
        public string C_REMARK { get; set; }
        public string C_BUSINESS_DEPT { get; set; }
        public string C_BUSINESS_TYPE { get; set; }
        public string C_SALESMAN { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_UNITPRICE { get; set; }
        public string N_MONEY { get; set; }
        public string C_FREE1 { get; set; }
        public string C_FREE2 { get; set; }
        public string C_FREE3 { get; set; }
    }
}
