//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMQ_QUALITY_MAIN
    {
        public string C_ID { get; set; }
        public string C_QUEST_ID { get; set; }
        public string C_PROD_KIND_ID { get; set; }
        public string C_SHIPVIA { get; set; }
        public Nullable<System.DateTime> D_SHIP_START_DT { get; set; }
        public Nullable<System.DateTime> D_SHIP_END_DT { get; set; }
        public Nullable<decimal> N_PARENT_REMAIN_WGT { get; set; }
        public Nullable<decimal> N_MIDDLE_REMAIN_WGT { get; set; }
        public string C_AREA { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_CUST_TYPE { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_TEL { get; set; }
        public string C_NAME { get; set; }
        public string C_STL_GRD_CLASS { get; set; }
        public string C_PROD_USE { get; set; }
        public Nullable<decimal> N_OBJECT_COUNT_WGT { get; set; }
        public string C_OBJECT_CONTENT { get; set; }
        public string C_TECH_DESC { get; set; }
        public string C_SITE_SURVEY_CONTENT { get; set; }
        public Nullable<short> N_PARENT_QUA { get; set; }
        public Nullable<short> N_QUEST_QUA { get; set; }
        public Nullable<short> N_MIDDLE_QUA { get; set; }
        public Nullable<short> N_ELSE_QUA { get; set; }
        public string C_SITE_SURVEY_EMP { get; set; }
        public string C_DEPT { get; set; }
        public string C_REMARK { get; set; }
        public string C_CUST_MAKING { get; set; }
        public Nullable<System.DateTime> C_CUST_MAKING_DT { get; set; }
        public string C_XG_MODIFY { get; set; }
        public Nullable<System.DateTime> C_XG_MODEIFY_DT { get; set; }
        public string C_APPROVER { get; set; }
        public Nullable<System.DateTime> D_APPROVER_DT { get; set; }
        public string C_FLOW_ID { get; set; }
        public short N_STATUS { get; set; }
        public Nullable<short> N_FLAG { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_DEPT2 { get; set; }
        public string C_DEPT3 { get; set; }
        public string C_DEPT4 { get; set; }
    }
}
