//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMQ_QUA_MAIN
    {
        public string C_ID { get; set; }
        public string C_AREA_ID { get; set; }
        public string C_DISTRIBUTOR { get; set; }
        public string C_DIRECTUSER { get; set; }
        public string C_CONTACT { get; set; }
        public string C_CON_PHONE { get; set; }
        public string C_GRD { get; set; }
        public string C_PROD_USE { get; set; }
        public Nullable<System.DateTime> D_SHIP_START_DT { get; set; }
        public Nullable<System.DateTime> D_SHIP_END_DT { get; set; }
        public Nullable<decimal> N_OBJECT_COUNT_WGT { get; set; }
        public string C_OBJECT_CONTENT { get; set; }
        public string C_TECH_DESC { get; set; }
        public string C_SITE_SURVEY_CONTENT { get; set; }
        public Nullable<short> N_PARENT_QUA { get; set; }
        public Nullable<short> N_QUEST_QUA { get; set; }
        public Nullable<short> N_MIDDLE_QUA { get; set; }
        public Nullable<short> N_ELSE_QUA { get; set; }
        public string C_DEPT { get; set; }
        public string C_QUALITY_DEPT { get; set; }
        public string C_TECHNOLOGY { get; set; }
        public string C_QT { get; set; }
        public string C_REMARK { get; set; }
        public string C_CUST_MAKING { get; set; }
        public Nullable<System.DateTime> D_CUST_MAKING_DT { get; set; }
        public string C_QUALITY_RESULT { get; set; }
        public string C_OBJECTION_TYPE { get; set; }
        public string C_OURREASONS { get; set; }
        public Nullable<System.DateTime> D_FEEDBACK_AREA { get; set; }
        public string C_EFFECT_VALID { get; set; }
        public string C_PRECC_RESULT { get; set; }
        public Nullable<decimal> N_AMOUNT { get; set; }
        public Nullable<System.DateTime> D_COMPENSATION_DT { get; set; }
        public string C_STATE { get; set; }
        public string C_MONTH_AVERAGE { get; set; }
        public string C_SALESMAN { get; set; }
        public Nullable<short> N_FLAG { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public short N_STATUS { get; set; }
        public Nullable<System.DateTime> D_EMP_DT { get; set; }
        public string C_CRT_ID { get; set; }
        public Nullable<System.DateTime> D_CRT_DT { get; set; }
        public string C_NO { get; set; }
        public Nullable<short> N_CYCLE { get; set; }
        public string C_SALESID { get; set; }
        public string C_FLOWID { get; set; }
        public string C_APPROVEID { get; set; }
    }
}
