//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPA_KP_PLAN
    {
        public string C_ID { get; set; }
        public string C_FK { get; set; }
        public string C_STOVE_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<System.DateTime> D_START_TIME { get; set; }
        public Nullable<System.DateTime> D_END_TIME { get; set; }
        public decimal N_CN { get; set; }
        public Nullable<System.DateTime> D_PLAN_DATE { get; set; }
        public string C_REMARK { get; set; }
        public short N_STATUS { get; set; }
        public string C_CCM { get; set; }
        public Nullable<System.DateTime> D_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_END_TIME_SJ { get; set; }
        public string C_KP_CODE { get; set; }
        public short N_SORT { get; set; }
        public string C_MATRL_CODE_SLAB { get; set; }
        public string C_MATRL_NAME_SLAB { get; set; }
        public Nullable<long> N_SLAB_LENGTH { get; set; }
        public Nullable<decimal> N_SLAB_PW { get; set; }
        public string C_MATRL_CODE_KP { get; set; }
        public string C_MATRL_NAME_KP { get; set; }
        public string C_KP_SIZE { get; set; }
        public Nullable<long> N_KP_LENGTH { get; set; }
        public Nullable<decimal> N_KP_PW { get; set; }
        public string C_DHL { get; set; }
        public Nullable<System.DateTime> D_CAN_START_TIME { get; set; }
        public string C_DFP_RZ { get; set; }
        public string C_RZP_RZ { get; set; }
        public string C_DFP_YQ { get; set; }
        public string C_RZP_YQ { get; set; }
        public string C_SLAB_SIZE { get; set; }
    }
}
