//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPA_ROLL_PLAN
    {
        public string C_ID { get; set; }
        public string C_LINE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public System.DateTime D_PLAN_DATE { get; set; }
        public Nullable<System.DateTime> D_NEED_DATE { get; set; }
        public string C_REMARK { get; set; }
    }
}
