//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPB_STEEL_PRO_CONDITION_LOG
    {
        public string C_ID { get; set; }
        public string C_STL_GRD_TYPE { get; set; }
        public string C_STL_GRD_RANK { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STL_SCRAP_TYPE { get; set; }
        public string C_STL_SCRAP_FLIJ { get; set; }
        public string C_GOUTE { get; set; }
        public string C_TEASE_PERSON { get; set; }
        public string C_ADV_PRO_REQUIRE { get; set; }
        public short N_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_REMARK { get; set; }
        public string C_IS_BXG { get; set; }
        public Nullable<decimal> N_GROUP { get; set; }
        public string C_FK { get; set; }
        public string C_VERSION { get; set; }
    }
}
