//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPB_ROLL_XM
    {
        public string C_ID { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_MIN_SPEC { get; set; }
        public string C_MAX_SPEC { get; set; }
        public Nullable<short> N_SFQPWTS { get; set; }
        public string C_XMFS { get; set; }
        public Nullable<short> N_SFXMHPWTS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_SPEC_STR { get; set; }
        public string C_N_STDCODE { get; set; }
    }
}
