//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPB_BXGXMGZ
    {
        public string C_ID { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public string C_GZLX { get; set; }
        public Nullable<decimal> N_JSCN { get; set; }
        public Nullable<decimal> N_LTH { get; set; }
        public Nullable<decimal> N_TOTAL_CN { get; set; }
        public string C_IS_BXG { get; set; }
        public string C_REMARK { get; set; }
    }
}
