//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPB_LGGYK
    {
        public string C_ID { get; set; }
        public string C_STEELGRADEINDEX { get; set; }
        public string C_LADLE_BRICK { get; set; }
        public string C_LADLE_USE { get; set; }
        public string C_LADLE_PRE_STEELGRADE { get; set; }
        public string C_LADLE_STAY { get; set; }
        public string C_BOF_TYPE { get; set; }
        public string C_LADLE_TAPPED_PROC { get; set; }
        public string C_LF_TYPE { get; set; }
        public string C_RH_TYPE { get; set; }
        public string C_CASTER_TYPE { get; set; }
        public Nullable<int> C_HOT_SEND_FLAG { get; set; }
        public string C_C_MIN { get; set; }
        public string C_C_AIM { get; set; }
        public string C_C_MAX { get; set; }
        public string C_SI_MIN { get; set; }
        public string C_SI_AIM { get; set; }
        public string C_SI_MAX { get; set; }
        public string C_MN_MIN { get; set; }
        public string C_MN_AIM { get; set; }
        public string C_MN_MAX { get; set; }
        public string C_P_MIN { get; set; }
        public string C_P_AIM { get; set; }
        public string C_P_MAX { get; set; }
        public string C_S_MIN { get; set; }
        public string C_S_AIM { get; set; }
        public string C_S_MAX { get; set; }
        public string C_CU_MIN { get; set; }
        public string C_CU_AIM { get; set; }
        public string C_CU_MAX { get; set; }
        public string C_NI_MIN { get; set; }
        public string C_NI_AIM { get; set; }
        public string C_NI_MAX { get; set; }
        public string C_CR_MIN { get; set; }
        public string C_CR_AIM { get; set; }
        public string C_CR_MAX { get; set; }
        public string C_MO_MIN { get; set; }
        public string C_MO_AIM { get; set; }
        public string C_MO_MAX { get; set; }
        public string C_V_MIN { get; set; }
        public string C_V_AIM { get; set; }
        public string C_V_MAX { get; set; }
        public string C_NB_MIN { get; set; }
        public string C_NB_AIM { get; set; }
        public string C_NB_MAX { get; set; }
        public string C_AL_MIN { get; set; }
        public string C_AL_AIM { get; set; }
        public string C_AL_MAX { get; set; }
        public string C_ALS_MIN { get; set; }
        public string C_ALS_AIM { get; set; }
        public string C_ALS_MAX { get; set; }
        public string C_TI_MIN { get; set; }
        public string C_TI_AIM { get; set; }
        public string C_TI_MAX { get; set; }
        public string C_B_MIN { get; set; }
        public string C_B_AIM { get; set; }
        public string C_B_MAX { get; set; }
        public string C_SB_MIN { get; set; }
        public string C_SB_AIM { get; set; }
        public string C_SB_MAX { get; set; }
        public string C_SN_MIN { get; set; }
        public string C_SN_AIM { get; set; }
        public string C_SN_MAX { get; set; }
        public string C_AS_MIN { get; set; }
        public string C_AS_AIM { get; set; }
        public string C_AS_MAX { get; set; }
        public string C_ZN_MIN { get; set; }
        public string C_ZN_AIM { get; set; }
        public string C_ZN_MAX { get; set; }
        public string C_ZR_MIN { get; set; }
        public string C_ZR_AIM { get; set; }
        public string C_ZR_MAX { get; set; }
        public string C_CA_MIN { get; set; }
        public string C_CA_AIM { get; set; }
        public string C_CA_MAX { get; set; }
        public string C_W_MIN { get; set; }
        public string C_W_AIM { get; set; }
        public string C_W_MAX { get; set; }
        public string C_PB_MIN { get; set; }
        public string C_PB_AIM { get; set; }
        public string C_PB_MAX { get; set; }
        public string C_RE_MIN { get; set; }
        public string C_RE_AIM { get; set; }
        public string C_RE_MAX { get; set; }
        public string C_CEQ_MIN { get; set; }
        public string C_CEQ_AIM { get; set; }
        public string C_CEQ_MAX { get; set; }
        public string C_N_MIN { get; set; }
        public string C_N_AIM { get; set; }
        public string C_N_MAX { get; set; }
        public string C_H_MIN { get; set; }
        public string C_H_AIM { get; set; }
        public string C_H_MAX { get; set; }
        public string C_O_MIN { get; set; }
        public string C_O_AIM { get; set; }
        public string C_O_MAX { get; set; }
        public string C_CRNI_MIN { get; set; }
        public string C_CRNI_AIM { get; set; }
        public string C_CRNI_MAX { get; set; }
        public string C_CRCU_MIN { get; set; }
        public string C_CRCU_AIM { get; set; }
        public string C_CRCU_MAX { get; set; }
        public string C_CRNICU_MIN { get; set; }
        public string C_CRNICU_AIM { get; set; }
        public string C_CRNICU_MAX { get; set; }
        public string C_OTHER1_MIN { get; set; }
        public string C_OTHER1_AIM { get; set; }
        public string C_OTHER1_MAX { get; set; }
        public string C_OTHER2_MIN { get; set; }
        public string C_OTHER2_AIM { get; set; }
        public string C_OTHER2_MAX { get; set; }
        public string C_OTHER3_MIN { get; set; }
        public string C_OTHER3_AIM { get; set; }
        public string C_OTHER3_MAX { get; set; }
        public string C_AOD_TYPE { get; set; }
        public string C_NAME { get; set; }
    }
}
