//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPC_PLAN_SMS
    {
        public string C_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public string C_CON_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_FREE1 { get; set; }
        public string C_FREE2 { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_DESIGN_NO { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<System.DateTime> D_NEED_DT { get; set; }
        public Nullable<System.DateTime> D_DELIVERY_DT { get; set; }
        public System.DateTime D_DT { get; set; }
        public short N_STATUS { get; set; }
        public Nullable<long> N_TYPE { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_ISSUE_EMP_ID { get; set; }
        public string C_PRD_EMP_ID { get; set; }
        public string C_CCM_NO { get; set; }
        public string C_RH { get; set; }
        public string C_LF { get; set; }
        public string C_KP { get; set; }
        public int N_HL_TIME { get; set; }
        public string C_HL { get; set; }
        public int N_DFP_HL_TIME { get; set; }
        public string C_DFP_HL { get; set; }
        public string C_XM { get; set; }
        public string C_ROUTE { get; set; }
        public string C_MATRL_CODE_SLAB { get; set; }
        public string C_MATRL_NAME_SLAB { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public Nullable<long> N_SLAB_LENGTH { get; set; }
        public Nullable<decimal> N_SLAB_PW { get; set; }
        public string C_MATRL_CODE_KP { get; set; }
        public string C_MATRL_NAME_KP { get; set; }
        public string C_KP_SIZE { get; set; }
        public Nullable<long> N_KP_LENGTH { get; set; }
        public Nullable<decimal> N_KP_PW { get; set; }
        public Nullable<decimal> N_GROUP { get; set; }
        public Nullable<decimal> N_SORT { get; set; }
        public string C_XC { get; set; }
        public string C_SL { get; set; }
        public string C_WL { get; set; }
        public Nullable<decimal> N_MACH_WGT_CCM { get; set; }
        public Nullable<decimal> N_ZJCLS { get; set; }
        public string C_BY1 { get; set; }
        public string C_BY2 { get; set; }
        public string C_BY3 { get; set; }
        public string C_BY4 { get; set; }
        public string C_BY5 { get; set; }
        public string C_LGJH { get; set; }
        public string C_ZL_ID { get; set; }
        public string C_LF_ID { get; set; }
        public string C_RH_ID { get; set; }
        public Nullable<decimal> N_SLAB_WIDTH { get; set; }
        public Nullable<decimal> N_SLAB_THICK { get; set; }
        public string C_DFP_RZ { get; set; }
        public string C_RZP_RZ { get; set; }
        public string C_DFP_YQ { get; set; }
        public string C_RZP_YQ { get; set; }
        public string C_XM_YQ { get; set; }
        public Nullable<int> N_KPJRL_WD { get; set; }
        public Nullable<int> N_KPJRL_SJ { get; set; }
        public Nullable<decimal> N_TSL { get; set; }
        public string C_CCM_CODE { get; set; }
        public string C_CCM_DESC { get; set; }
        public string C_TL { get; set; }
        public Nullable<decimal> N_ZJCLS_MIN { get; set; }
        public Nullable<decimal> N_ZJCLS_MAX { get; set; }
        public string C_STL_GRD_TYPE { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_INITIALIZE_ITEM_ID { get; set; }
    }
}
