//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPC_PLAN_ROLL
    {
        public string C_ID { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_ORDER_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<short> N_USER_LEV { get; set; }
        public Nullable<short> N_STL_GRD_LEV { get; set; }
        public string C_ORDER_LEV { get; set; }
        public string C_QUALIRY_LEV { get; set; }
        public Nullable<System.DateTime> D_NEED_DT { get; set; }
        public Nullable<System.DateTime> D_DELIVERY_DT { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public string C_LINE_DESC { get; set; }
        public string C_LINE_CODE { get; set; }
        public Nullable<System.DateTime> D_P_START_TIME { get; set; }
        public Nullable<System.DateTime> D_P_END_TIME { get; set; }
        public Nullable<decimal> N_PROD_TIME { get; set; }
        public Nullable<short> N_SORT { get; set; }
        public Nullable<short> N_ROLL_PROD_WGT { get; set; }
        public string C_ROLL_PROD_EMP_ID { get; set; }
        public string C_STL_ROL_DT { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_PACK { get; set; }
        public string C_DESIGN_NO { get; set; }
        public string C_LINT_ID { get; set; }
        public Nullable<System.DateTime> D_START_TIME { get; set; }
        public Nullable<System.DateTime> D_END_TIME { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_MACH_WGT { get; set; }
        public string C_FREE_TERM { get; set; }
        public string C_FREE_TERM2 { get; set; }
        public string C_AREA { get; set; }
        public string C_PCLX { get; set; }
        public string C_RH { get; set; }
        public string C_LF { get; set; }
        public string C_KP { get; set; }
        public Nullable<int> N_HL_TIME { get; set; }
        public string C_HL { get; set; }
        public Nullable<int> N_DFP_HL_TIME { get; set; }
        public string C_DFP_HL { get; set; }
        public string C_XM { get; set; }
        public string C_ROUTE { get; set; }
        public Nullable<decimal> N_DIAMETER { get; set; }
        public string C_XM_YQ { get; set; }
        public Nullable<int> N_JRL_WD { get; set; }
        public Nullable<int> N_JRL_SJ { get; set; }
    }
}
