//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPO_APS_CONFIG
    {
        public string C_ID { get; set; }
        public Nullable<short> N_LZDHL { get; set; }
        public Nullable<short> N_LZKP { get; set; }
        public Nullable<short> N_DHLKP { get; set; }
        public Nullable<short> N_KPXHL { get; set; }
        public Nullable<short> N_KPZG { get; set; }
        public Nullable<short> N_XHLZG { get; set; }
        public Nullable<short> N_5LZZS { get; set; }
        public Nullable<short> N_7LZZS { get; set; }
        public Nullable<short> N_3LZZS { get; set; }
        public Nullable<short> N_4LZZS { get; set; }
        public Nullable<short> N_6LZZS { get; set; }
        public Nullable<short> N_5LZZL { get; set; }
        public Nullable<short> N_7LZZL { get; set; }
        public Nullable<short> N_3LZZL { get; set; }
        public Nullable<short> N_4LZZL { get; set; }
        public Nullable<short> N_6LZZL { get; set; }
        public Nullable<short> N_RHLS { get; set; }
        public Nullable<short> N_HLGLS { get; set; }
        public Nullable<short> N_HLGSJ { get; set; }
        public Nullable<short> N_TGJSCL { get; set; }
        public Nullable<short> N_BXGJSCL { get; set; }
        public Nullable<short> N_1KPJSCL { get; set; }
        public Nullable<short> N_2KPJSCL { get; set; }
        public Nullable<short> N_KPL { get; set; }
        public Nullable<short> N_XML { get; set; }
    }
}
