//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_INITIALIZE_ORDER
    {
        public string C_ID { get; set; }
        public string C_INITIALIZE_ID { get; set; }
        public string C_ORDER_ID { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<decimal> N_MACH_WGT { get; set; }
        public string C_DESIGN_NO { get; set; }
        public decimal N_STATUS { get; set; }
        public decimal N_FLAG { get; set; }
        public string C_RH { get; set; }
        public string C_LF { get; set; }
        public string C_KP { get; set; }
        public Nullable<decimal> N_HL_TIME { get; set; }
        public string C_HL { get; set; }
        public Nullable<decimal> N_DFP_HL_TIME { get; set; }
        public string C_DFP_HL { get; set; }
        public string C_XM { get; set; }
        public string C_ROLL_STA_ID { get; set; }
        public string C_CCM_STA_ID { get; set; }
        public Nullable<decimal> N_MACH_WGT_CCM { get; set; }
        public Nullable<decimal> N_LGPC_STATUS { get; set; }
        public Nullable<decimal> N_EXEC_STATUS { get; set; }
        public Nullable<decimal> N_ROLL_PROD_WGT { get; set; }
        public Nullable<decimal> N_SMS_PROD_WGT { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_MATRL_CODE_SLAB { get; set; }
        public string C_MATRL_NAME_SLAB { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public Nullable<long> N_SLAB_LENGTH { get; set; }
        public Nullable<decimal> N_SLAB_PW { get; set; }
        public string C_MATRL_CODE_KP { get; set; }
        public string C_MATRL_NAME_KP { get; set; }
        public string C_KP_SIZE { get; set; }
        public Nullable<long> N_KP_LENGTH { get; set; }
        public Nullable<decimal> N_KP_PW { get; set; }
        public string C_ROUTE { get; set; }
        public Nullable<decimal> N_GROUP { get; set; }
        public Nullable<decimal> N_SORT { get; set; }
        public string C_XC { get; set; }
        public string C_SL { get; set; }
        public string C_WL { get; set; }
        public string C_ORDERNO { get; set; }
        public string C_CONNO { get; set; }
    }
}
