//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_CAST_PLAN
    {
        public string C_ID { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_CONTRACT_ID { get; set; }
        public string C_PLAN_DEPT { get; set; }
        public string C_EXECUTE_DEPT { get; set; }
        public Nullable<System.DateTime> D_PLANEXECUTE_DATE { get; set; }
        public Nullable<System.DateTime> D_ACTUALEXECUTE_DATE { get; set; }
        public string C_PLANNER { get; set; }
        public string C_PRE_LOTNO { get; set; }
        public string C_PRE_HEAT_ID { get; set; }
        public string C_PRE_STEELGRADEINDEX { get; set; }
        public string C_PRE_STEELGRADE { get; set; }
        public Nullable<decimal> N_AIM_TAPPED_WEIGHT { get; set; }
        public string C_CASTER_ID { get; set; }
        public string C_BOF_ID { get; set; }
        public string C_LF_ID { get; set; }
        public string C_RH_ID { get; set; }
        public string N_BOF_STATUS { get; set; }
        public string N_LF_STATUS { get; set; }
        public string N_RH_STATUS { get; set; }
        public string N_CASTER_STATUS { get; set; }
        public string N_S_IDE_STATUS { get; set; }
        public string C_HEAT_ID { get; set; }
        public string C_CASTER_NO { get; set; }
        public string C_CASTING_HEAT_CNT { get; set; }
        public Nullable<System.DateTime> D_AIM_IRONPREPARED_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_BOFSTART_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_BOFTAPPED_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_TAPPEDSIDEEND_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_LFARRIVAL_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_LFSTART_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_LFEND_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_LFLEAVE_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_RHARRIVAL_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_RHSTART_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_RHEND_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_RHLEAVE_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_CASTERARRIVAL_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_CASTINGSTART_TIME { get; set; }
        public Nullable<System.DateTime> D_AIM_CASTINGEND_TIME { get; set; }
        public string C_FIR_HEAT_FLAG { get; set; }
        public string DIV_HEAT_ID { get; set; }
        public string C_TEAM_ID { get; set; }
        public string C_SHIFT_ID { get; set; }
        public string STEELGRADEINDEX { get; set; }
        public string C_PLAN_ORD__ID { get; set; }
        public string C_HOT_SEND_FLAG { get; set; }
        public string C_STEEL_RETURN_FLAG { get; set; }
        public string C_STEEL_BACK_FLAG { get; set; }
        public string C_TREAT_SEQ { get; set; }
        public string C_DESTITATION { get; set; }
        public string C_NEW_BOF_FLAG { get; set; }
        public string C_REFINE_TYPE { get; set; }
        public string C_LENGTH { get; set; }
        public string C_W_IDTH { get; set; }
        public string C_THICKNESS { get; set; }
        public string C_AOD_ID { get; set; }
        public string C_DEP_ID { get; set; }
        public string C_RHL_ID { get; set; }
        public string C_DEP_STATUS { get; set; }
        public string C_RHL_STATUS { get; set; }
        public string C_AOD_STATUS { get; set; }
        public string C_INITIALIZE_ITEM { get; set; }
        public string C_IS_TO_MES { get; set; }
        public string C_MES_PLAN_ID { get; set; }
        public string C_LD_DESC { get; set; }
        public string C_LF_DESC { get; set; }
        public string C_RH_DESC { get; set; }
        public string C_CC_DESC { get; set; }
        public Nullable<System.DateTime> D_DOWN_TIME { get; set; }
    }
}
