//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_SLAB_PLAN_XM
    {
        public string C_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_XM_DESC { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> C_SPEC { get; set; }
        public Nullable<decimal> N_LTH { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<decimal> N_QTY { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<System.DateTime> D_PLAN_DT { get; set; }
        public Nullable<System.DateTime> D_PLAN_START { get; set; }
        public Nullable<System.DateTime> D_PLAN_END { get; set; }
        public decimal N_STATUS { get; set; }
        public Nullable<decimal> N_ACT_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<decimal> N_ACT_QTY { get; set; }
    }
}
