//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_INITIALIZE_LINE
    {
        public string C_ID { get; set; }
        public string C_INITIALIZE_ITEM_ID { get; set; }
        public Nullable<decimal> N_CAPACITY { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_ZL_STA_ID { get; set; }
        public string C_JL_STA_ID { get; set; }
        public string C_ZK_STA_ID { get; set; }
        public string C_LZ_STA_ID { get; set; }
        public string C_ZL_STA_DESC { get; set; }
        public string C_JL_STA_DESC { get; set; }
        public string C_ZK_STA_DESC { get; set; }
        public string C_LZ_STA_DESC { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
