//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_LGPC_JCITEM
    {
        public string C_ID { get; set; }
        public string C_CCM_ID { get; set; }
        public string C_CCM_CODE { get; set; }
        public Nullable<decimal> N_GROUP { get; set; }
        public Nullable<decimal> N_TOTAL_WGT { get; set; }
        public Nullable<decimal> N_ZJCLS { get; set; }
        public Nullable<decimal> N_ZJCLZL { get; set; }
        public Nullable<decimal> N_MLZL { get; set; }
        public Nullable<decimal> N_SORT { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> N_PRODUCE_TIME { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<decimal> N_LS { get; set; }
    }
}
