//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_LGPC_LSB
    {
        public string C_ID { get; set; }
        public string C_CCM_ID { get; set; }
        public string C_CCM_CODE { get; set; }
        public Nullable<decimal> N_GROUP { get; set; }
        public Nullable<decimal> N_TOTAL_WGT { get; set; }
        public Nullable<decimal> N_ZJCLS { get; set; }
        public Nullable<decimal> N_ZJCLZL { get; set; }
        public Nullable<decimal> N_MLZL { get; set; }
        public Nullable<decimal> N_SORT { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> N_PRODUCE_TIME { get; set; }
        public Nullable<decimal> N_JSCN { get; set; }
        public string C_BY1 { get; set; }
        public string C_BY2 { get; set; }
        public string C_BY3 { get; set; }
        public string C_RH { get; set; }
        public string C_DFP_HL { get; set; }
        public string C_HL { get; set; }
        public string C_XM { get; set; }
        public decimal N_ORDER_LS { get; set; }
        public Nullable<System.DateTime> D_DFPHL_START_TIME { get; set; }
        public Nullable<System.DateTime> D_DFPHL_END_TIME { get; set; }
        public Nullable<System.DateTime> D_KP_START_TIME { get; set; }
        public Nullable<System.DateTime> D_KP_END_TIME { get; set; }
        public Nullable<System.DateTime> D_HL_START_TIME { get; set; }
        public Nullable<System.DateTime> D_HL_END_TIME { get; set; }
        public Nullable<System.DateTime> D_PLAN_KY_TIME { get; set; }
        public string C_PLAN_ROLL { get; set; }
        public Nullable<System.DateTime> D_ZZ_START_TIME { get; set; }
        public Nullable<System.DateTime> D_ZZ_END_TIME { get; set; }
        public Nullable<System.DateTime> D_XM_START_TIME { get; set; }
        public Nullable<System.DateTime> D_XM_END_TIME { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public string C_STL_GRD_TYPE { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public int N_DFP_HL_TIME { get; set; }
        public int N_HL_TIME { get; set; }
        public decimal N_XM_TIME { get; set; }
        public int N_GG { get; set; }
        public decimal N_CCM_TIME { get; set; }
        public string C_TJ_REMARK { get; set; }
        public string C_TL { get; set; }
        public short N_RH { get; set; }
        public short N_TL { get; set; }
        public short N_GZSL { get; set; }
        public string C_REMARK { get; set; }
        public short N_XM { get; set; }
        public short N_DHL { get; set; }
        public short N_HL { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<System.DateTime> D_P_START_TIME { get; set; }
        public Nullable<System.DateTime> D_P_END_TIME { get; set; }
        public short N_DFP_RZ { get; set; }
        public short N_RZP_RZ { get; set; }
        public string C_RH_SFJS { get; set; }
    }
}
