//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPP_INITIALIZE_STA
    {
        public string C_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<decimal> N_PRODUCIBILITY_TIME { get; set; }
        public Nullable<decimal> N_IMPACT_TIME { get; set; }
        public Nullable<decimal> N_CAPACITY { get; set; }
        public string C_PRO_CODE { get; set; }
        public string C_INITIALIZE_ITEM_ID { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STA_DESC { get; set; }
        public string C_PRO_ID { get; set; }
        public string C_STA_CODE { get; set; }
        public Nullable<System.DateTime> D_START_TIME { get; set; }
        public Nullable<System.DateTime> D_END_TIME { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
