//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQ_MODULE
    {
        public string C_ID { get; set; }
        public string C_CLASS { get; set; }
        public string C_MODULE { get; set; }
        public string C_CONENT { get; set; }
        public string C_XGEMP { get; set; }
        public string C_DEPT { get; set; }
        public string C_TEL { get; set; }
        public Nullable<System.DateTime> D_TIME { get; set; }
        public string C_ICT { get; set; }
        public string C_RESULT { get; set; }
        public Nullable<System.DateTime> D_ICTTIME { get; set; }
        public string C_REAMRK { get; set; }
    }
}
