//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQB_TRUCK
    {
        public string C_ID { get; set; }
        public System.DateTime D_TRUCK_DT { get; set; }
        public string C_TRUCK_NUM { get; set; }
        public string C_SHIPMENT_BATCH { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_LOADING_QUANTITY { get; set; }
        public string C_CRE_ABRADE { get; set; }
        public string C_CRE_ABRADE_TICK { get; set; }
        public string C_BACK_ABRADE { get; set; }
        public string C_BACK_ABRADE_TICK { get; set; }
        public string C_SUPERINTENDENT { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
