//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQB_TSBZ_MAIN
    {
        public string C_ID { get; set; }
        public string C_XY_CODE { get; set; }
        public string C_XY_DESC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_ROUTE { get; set; }
        public string C_EDITION { get; set; }
        public short N_IS_CHECK { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_IS_OFTEN { get; set; }
        public string C_REMARK_JB { get; set; }
        public Nullable<short> N_EDIT_NUM { get; set; }
    }
}
