//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQB_STD_MAIN_COPY
    {
        public string C_ID { get; set; }
        public string C_STD_TYPE { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STD_DESC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_USES { get; set; }
        public Nullable<short> N_EDIT_NUM { get; set; }
        public string C_EDITION { get; set; }
        public string C_IS_LF { get; set; }
        public string C_IS_RH { get; set; }
        public string C_IS_HL { get; set; }
        public string C_IS_XM { get; set; }
        public string C_IRON_REQUIRE { get; set; }
        public string C_STOCK_REQUIRE { get; set; }
        public string C_DELIVERY_STATE { get; set; }
        public string C_PHYSICS_TIME { get; set; }
        public short N_IS_CHECK { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_IS_DESIGN { get; set; }
        public string C_IS_BXG { get; set; }
    }
}
