//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQB_STD_SAMPLING
    {
        public string C_ID { get; set; }
        public string C_STD_MAIN_ID { get; set; }
        public string C_SAMPLING_ID { get; set; }
        public string C_NUMBER { get; set; }
        public string C_SAM_SPE { get; set; }
        public string C_SAM_LEN { get; set; }
        public string C_SAM_METHOD { get; set; }
        public string C_SAM_NUM { get; set; }
        public string C_RECHECK_NUM { get; set; }
        public string C_NUM_UNIT { get; set; }
        public string C_SAM_SECTION { get; set; }
        public string C_TEST_UNIT { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    
        public virtual TQB_SAMPLING TQB_SAMPLING { get; set; }
    }
}
