//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQB_FAULT_STATISTICS
    {
        public string C_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_TEST_QUANTITY { get; set; }
        public string C_FACE_FAULT_QUA { get; set; }
        public string C_FACE_FAULT_CAUSE { get; set; }
        public string C_FACE_DUTY_DEP { get; set; }
        public string C_WAREHOUSE_QUA { get; set; }
        public string C_WAR_FAULT_CAUSE { get; set; }
        public string C_WAR_DUTY_DEP { get; set; }
        public string C_ALTER_DECIDE_NUM { get; set; }
        public string C_ALTER_DECIDE_CAUSE { get; set; }
        public string C_ALTER_DECIDE_DEP { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
