//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_ZZS_INFO
    {
        public string C_ID { get; set; }
        public string C_FYDH { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<System.DateTime> D_CKSJ { get; set; }
        public Nullable<decimal> N_JZ { get; set; }
        public Nullable<short> N_NUM { get; set; }
        public string C_CH { get; set; }
        public string C_PDF_NAME { get; set; }
        public string C_PDF_PATCH { get; set; }
        public short N_PRINT_NUM { get; set; }
        public string C_ZSH { get; set; }
        public string C_QZR { get; set; }
        public System.DateTime D_QZRQ { get; set; }
        public string C_BY1 { get; set; }
        public string C_BY2 { get; set; }
        public string C_BY3 { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_IMG { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_SH_NAME { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_STD_JH { get; set; }
        public string C_ZLDJ { get; set; }
        public string C_JH_STATE { get; set; }
        public string C_JSXYH { get; set; }
        public string C_XKZH { get; set; }
        public string C_PRINT_EMP { get; set; }
        public Nullable<System.DateTime> D_PRINT_DT { get; set; }
    }
}
