//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_WAREHOUSE_CHECK_SLAB
    {
        public string C_ID { get; set; }
        public string C_SLAB_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public decimal N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public Nullable<int> N_LEN { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public Nullable<System.DateTime> D_WAREHOUSE_IN { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public string C_REASON_NAME { get; set; }
        public string C_REASON_CODE { get; set; }
        public string C_REASON_DEPMT_ID { get; set; }
        public string C_REASON_DEPMT_DESC { get; set; }
        public string C_SUGGESTION { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_CHECK_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_CHECK_DT { get; set; }
    }
}
