//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_COMPRE_SLAB
    {
        public string C_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public decimal N_WGT { get; set; }
        public Nullable<int> N_QUA { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SPEC { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public string C_RESULT_FACE { get; set; }
        public string C_REASON_NAME { get; set; }
        public string C_REASON_CODE { get; set; }
        public Nullable<System.DateTime> D_DP_DT { get; set; }
        public string C_RESULT_ELE { get; set; }
        public string C_RESULT_PHY { get; set; }
        public string C_RESULT_ALL { get; set; }
        public Nullable<System.DateTime> D_RESALL_DT { get; set; }
        public string C_RESULT_PEOPLE { get; set; }
        public Nullable<System.DateTime> D_RESPEO_DT { get; set; }
        public string C_QR_STATE { get; set; }
        public string C_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_RESULT_PHYSEC { get; set; }
        public string C_RESULT_PHYFINAL { get; set; }
        public string C_DESIGN_NO { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<int> N_LEN { get; set; }
    }
}
