//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_ROLL_COMMUTE
    {
        public string C_ID { get; set; }
        public string C_ROLL_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_STA_DESC { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_TICK_NO { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STL_GRD_BEFORE { get; set; }
        public string C_STD_CODE_BEFORE { get; set; }
        public string C_SPEC_BEFORE { get; set; }
        public string C_MAT_CODE_BEFORE { get; set; }
        public string C_MAT_DESC_BEFORE { get; set; }
        public Nullable<System.DateTime> D_COMMUTE_DATE { get; set; }
        public string C_STL_GRD_AFTER { get; set; }
        public string C_STD_CODE_AFTER { get; set; }
        public string C_SPEC_AFTER { get; set; }
        public string C_MAT_CODE_AFTER { get; set; }
        public string C_MAT_DESC_AFTER { get; set; }
        public string C_REASON_DEPMT_ID { get; set; }
        public string C_REASON_DEPMT_DESC { get; set; }
        public string C_GP_TYPE { get; set; }
        public string C_SCUTCHEON { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_MASTER_ID { get; set; }
        public string C_GP_BEFORE_ID { get; set; }
        public string C_GP_AFTER_ID { get; set; }
        public string C_ZYX1_BEFORE { get; set; }
        public string C_ZYX2_BEFORE { get; set; }
        public string C_ZYX1_AFTER { get; set; }
        public string C_ZYX2_AFTER { get; set; }
        public string C_JUDGE_LEV_BP_BEFORE { get; set; }
        public string C_JUDGE_LEV_BP_AFTER { get; set; }
        public string C_BZYQ_BEFORE { get; set; }
        public string C_BZYQ_AFTER { get; set; }
        public string C_COMMUTE_REASON { get; set; }
    }
}
