//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_RECHECK
    {
        public string C_ID { get; set; }
        public string C_PHYSICS_CODE { get; set; }
        public string C_PHYSICS_NAME { get; set; }
        public string C_CHARACTER_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_ITEM_NAME { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public string C_STA_ID { get; set; }
        public string C_DISPOSAL { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<short> N_NUMBER { get; set; }
        public short N_IS_QR { get; set; }
        public string C_QR_USER_ID { get; set; }
        public Nullable<System.DateTime> D_QR_MOD { get; set; }
        public string C_TICK_NO { get; set; }
        public Nullable<short> N_RECHECK { get; set; }
        public string C_ZZ_USER_ID { get; set; }
        public Nullable<System.DateTime> D_ZZ_MOD { get; set; }
        public string C_ZZJG { get; set; }
    }
}
