//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_CFXN_NC
    {
        public string C_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_SAMPLE_CODE { get; set; }
        public string C_RESULT { get; set; }
        public string C_CHECKITEM_CODE { get; set; }
        public string C_CHECKITEM_NAME { get; set; }
        public System.DateTime D_TB_TIME { get; set; }
        public string C_PCI_NAME { get; set; }
        public string C_PCI_CODE { get; set; }
    }
}
