//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQC_TP_SLAB_COMMUTE
    {
        public string C_ID { get; set; }
        public string C_SLAB_MAIN_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<decimal> N_LEN_BEFORE { get; set; }
        public Nullable<decimal> N_LEN_AFTER { get; set; }
        public string C_STL_GRD_BEFORE { get; set; }
        public string C_STD_CODE_BEFORE { get; set; }
        public string C_SPEC_BEFORE { get; set; }
        public string C_MAT_CODE_BEFORE { get; set; }
        public string C_MAT_DESC_BEFORE { get; set; }
        public string C_STL_GRD_AFTER { get; set; }
        public string C_STD_CODE_AFTER { get; set; }
        public string C_SPEC_AFTER { get; set; }
        public string C_MAT_CODE_AFTER { get; set; }
        public string C_MAT_DESC_AFTER { get; set; }
        public string C_REASON_DEPMT_ID { get; set; }
        public string C_REASON_DEPMT_DESC { get; set; }
        public string C_ZYX1_BEFORE { get; set; }
        public string C_ZYX2_BEFORE { get; set; }
        public string C_ZYX1_AFTER { get; set; }
        public string C_ZYX2_AFTER { get; set; }
        public string C_JUDGE_LEV_BP_BEFORE { get; set; }
        public string C_JUDGE_LEV_BP_AFTER { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_COMMUTE_SQ { get; set; }
        public string C_CHECK_ZKB { get; set; }
        public string C_ZKB_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_CHECK_ZKB_DATE { get; set; }
        public string C_CZYJ_ZKB { get; set; }
        public string C_CHECK_XC { get; set; }
        public string C_XC_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_CHECK_XC_DATE { get; set; }
        public string C_CZYJ_XC { get; set; }
        public string C_CHECK_LG { get; set; }
        public string C_LG_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_CHECK_LG_DATE { get; set; }
        public string C_CZYJ_LG { get; set; }
        public string C_CHECK_JSZX { get; set; }
        public string C_JSZX_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_CHECK_JSZX_DATE { get; set; }
        public string C_CZYJ_JSZX { get; set; }
        public string C_COMMUTE_REASON { get; set; }
        public Nullable<System.DateTime> D_COMMUTE_DATE { get; set; }
        public Nullable<short> N_IS_SH { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_REMARK1 { get; set; }
        public string C_REMARK2 { get; set; }
        public string C_REMARK3 { get; set; }
    }
}
