//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQR_ZBS_ITEM
    {
        public string C_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_CF1 { get; set; }
        public string C_CF2 { get; set; }
        public string C_CF3 { get; set; }
        public string C_CF4 { get; set; }
        public string C_CF5 { get; set; }
        public string C_CF6 { get; set; }
        public string C_CF7 { get; set; }
        public string C_CF8 { get; set; }
        public string C_CF9 { get; set; }
        public string C_CF10 { get; set; }
        public string C_CF11 { get; set; }
        public string C_CF12 { get; set; }
        public string C_XN01 { get; set; }
        public string C_XN02 { get; set; }
        public string C_XN03 { get; set; }
        public string C_XN04 { get; set; }
        public string C_XN05 { get; set; }
        public string C_XN06 { get; set; }
        public string C_XN07 { get; set; }
        public string C_XN08 { get; set; }
        public string C_XN09 { get; set; }
        public string C_XN10 { get; set; }
        public string C_XN11 { get; set; }
        public string C_XN12 { get; set; }
        public string C_XN13 { get; set; }
        public string C_XN14 { get; set; }
        public string C_XN15 { get; set; }
        public string C_XN16 { get; set; }
        public string C_XN17 { get; set; }
        public string C_XN18 { get; set; }
        public string C_XN19 { get; set; }
        public string C_XN20 { get; set; }
        public string C_XN21 { get; set; }
        public string C_XN22 { get; set; }
        public string C_XN23 { get; set; }
        public string C_XN24 { get; set; }
        public string C_XN25 { get; set; }
        public System.DateTime D_CREAT_TIME { get; set; }
        public Nullable<short> N_ORDER { get; set; }
    }
}
