//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQR_GRADE
    {
        public string C_ID { get; set; }
        public System.DateTime D_RATE_DT { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_BATCH_NO_KP { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_QUA { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_LG_GX_GRADE { get; set; }
        public string C_LG_GRADE_CAUSE { get; set; }
        public string C_XC_GX_GRADE { get; set; }
        public string C_XC_GRADE_CAUSE { get; set; }
        public string C_CF_GRADE { get; set; }
        public string C_CF_GRADE_CAUSE { get; set; }
        public string C_XN_GRADE { get; set; }
        public string C_XN_GRADE_CAUSE { get; set; }
        public string C_FACE_GRADE { get; set; }
        public string C_FACE_GRADE_CAUSE { get; set; }
        public string C_CP_ZH_GRADE { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
