//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_COGDOWN_LOG
    {
        public string C_ID { get; set; }
        public string C_TRC_ROLL_MAIN_ID { get; set; }
        public string C_TRC_PLAN_ROLL_ID { get; set; }
        public Nullable<decimal> N_QUA_TOTAL { get; set; }
        public Nullable<decimal> N_WGT_TOTAL { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public Nullable<decimal> N_ROLL_STATE { get; set; }
        public string C_REMARK { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_QUA_REMOVE { get; set; }
        public Nullable<decimal> N_WGT_REMOVE { get; set; }
        public Nullable<decimal> N_QUA_RETRUN { get; set; }
        public Nullable<decimal> N_WGT_RETRUN { get; set; }
        public Nullable<decimal> N_QUA_JOIN { get; set; }
        public Nullable<decimal> N_WGT_JOIN { get; set; }
        public Nullable<decimal> N_QUA_EXIT { get; set; }
        public Nullable<decimal> N_WGT_EXIT { get; set; }
        public Nullable<decimal> N_QUA_CPHALF { get; set; }
        public Nullable<decimal> N_WGT_HALF { get; set; }
        public Nullable<decimal> N_QUA_CPWHOLE { get; set; }
        public Nullable<decimal> N_QUA_ELIM { get; set; }
        public Nullable<decimal> N_WGT_ELIM { get; set; }
        public string C_EMP_ID { get; set; }
        public decimal N_STATUS { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public Nullable<decimal> N_QUA_SL { get; set; }
        public Nullable<decimal> N_QUA_HG { get; set; }
        public Nullable<decimal> N_WGT_SL { get; set; }
        public Nullable<decimal> N_WGT_HG { get; set; }
        public string C_LOG_ID { get; set; }
        public string C_BATCH_NO { get; set; }
    }
}
