//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_MAIN_ITEM
    {
        public string C_ID { get; set; }
        public string C_ROLL_MAIN_ID { get; set; }
        public string C_SLAB_MAIN_ID { get; set; }
    }
}
