//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_TMLOG
    {
        public string C_ID { get; set; }
        public string C_ZKD_NO1 { get; set; }
        public string C_DH_ID { get; set; }
        public string C_MOVE_TYPE1 { get; set; }
        public string C_FYDH1 { get; set; }
        public string C_QTCKD_NO1 { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE { get; set; }
        public string C_ZKD_NO2 { get; set; }
        public string C_BARCODE { get; set; }
        public string C_MOVE_TYPE2 { get; set; }
        public string C_FYDH2 { get; set; }
        public string C_QTCKD_NO2 { get; set; }
    }
}
