//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_PDD_ITEM
    {
        public string C_YSDH { get; set; }
        public string C_MATCODE { get; set; }
        public string C_PCH { get; set; }
        public string C_SX { get; set; }
        public Nullable<decimal> C_ZCSL { get; set; }
        public Nullable<decimal> C_FZCZL { get; set; }
        public string C_FREE0 { get; set; }
        public string C_FREE1 { get; set; }
        public string C_FREE2 { get; set; }
        public string C_FREE3 { get; set; }
        public string C_FREE4 { get; set; }
        public string C_ID { get; set; }
        public Nullable<System.DateTime> D_INSERT { get; set; }
        public string C_REMARK { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_CK { get; set; }
        public string C_MATDESC { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> C_NC_SL { get; set; }
        public Nullable<decimal> C_NC_ZL { get; set; }
        public Nullable<decimal> C_CAP_SL { get; set; }
        public Nullable<decimal> C_CAP_ZL { get; set; }
        public Nullable<decimal> C_RF_SL { get; set; }
        public Nullable<decimal> C_RF_ZL { get; set; }
        public Nullable<decimal> C_RF_SJ_SL { get; set; }
        public Nullable<decimal> C_RF_SJ_ZL { get; set; }
        public Nullable<decimal> C_NC_CAP_SL { get; set; }
        public Nullable<decimal> C_NC_CAP_ZL { get; set; }
        public Nullable<decimal> C_RF_CAP_SL { get; set; }
        public Nullable<decimal> C_RF_CAP_ZL { get; set; }
        public Nullable<decimal> C_CAP_SJ_SL { get; set; }
        public Nullable<decimal> C_CAP_SJ_ZL { get; set; }
    }
}
