//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_QTCKD
    {
        public string C_ID { get; set; }
        public string C_QTCKD_NO { get; set; }
        public string C_LIC_PLA_NO { get; set; }
        public string C_ADDRESS { get; set; }
        public string C_CREATE_ID { get; set; }
        public Nullable<System.DateTime> D_CREATE_DT { get; set; }
        public string C_CHANGE_ID { get; set; }
        public Nullable<System.DateTime> D_CHANGE_DT { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_TYPE { get; set; }
        public string C_NCDJ { get; set; }
        public string C_CYS { get; set; }
        public string C_SHDW { get; set; }
        public Nullable<System.DateTime> D_FYSJ { get; set; }
        public string C_MBWH_ID { get; set; }
        public string C_MBWH_NAME { get; set; }
        public string C_TB { get; set; }
        public string C_CREATE_CODE { get; set; }
        public string C_LINEWH_CODE { get; set; }
    }
}
