//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_WGD_HANDLER
    {
        public string C_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_WGD_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_PLAN_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_STATUS { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_PACK { get; set; }
        public string C_FREE_TERM { get; set; }
        public string C_FREE_TERM2 { get; set; }
        public string C_MRSX { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_PCLX { get; set; }
        public string C_NEWMRSX { get; set; }
        public string C_NEWPCLX { get; set; }
        public string C_NEW_STD_CODE { get; set; }
        public string C_NEW_STL_GRD { get; set; }
        public string C_NEW_SPEC { get; set; }
        public string C_NEW_PACK { get; set; }
        public string C_NEW_FREE_TERM { get; set; }
        public string C_NEW_FREE_TERM2 { get; set; }
        public string C_NEW_MAT_CODE { get; set; }
        public string C_NEW_MAT_DESC { get; set; }
        public string C_SX { get; set; }
        public string C_NEW_SX { get; set; }
    }
}
