//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_WARM_FURNACE
    {
        public string C_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public Nullable<decimal> N_QUA_JOIN { get; set; }
        public Nullable<decimal> N_WGT_JOIN { get; set; }
        public string C_TRC_ROLL_MAIN_ID { get; set; }
        public Nullable<decimal> N_ROLL_STATE { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public Nullable<decimal> N_QUA_EXIT { get; set; }
        public Nullable<decimal> N_WGT_EXIT { get; set; }
        public Nullable<decimal> N_STATUS { get; set; }
        public string C_SLAB_MAIN_ID { get; set; }
        public string C_STOVE { get; set; }
        public Nullable<short> N_LEN { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
    }
}
