//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_WGD
    {
        public string C_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_PLANT { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_PLAN_ID { get; set; }
        public Nullable<decimal> N_QUA_PRODUCE { get; set; }
        public Nullable<decimal> N_WGT_PRODUCE { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> C_ROLL_STATE { get; set; }
        public string C_FUR_TYPE { get; set; }
        public string C_REMARK { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE { get; set; }
        public string C_PRODUCE_EMP_ID { get; set; }
        public string C_PRODUCE_SHIFT { get; set; }
        public string C_PRODUCE_GROUP { get; set; }
        public string C_SX { get; set; }
        public string C_PCLX { get; set; }
        public string C_MAIN_ID { get; set; }
        public string C_SCX_NC { get; set; }
        public string C_PACK { get; set; }
        public string C_FREE_TERM { get; set; }
        public string C_FREE_TERM2 { get; set; }
        public string C_AREA { get; set; }
        public string C_ZPDJBZ { get; set; }
        public decimal N_SCRF { get; set; }
        public string C_MRSX { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE_B { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE_E { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_PRODUCE_SHIFT_NAME { get; set; }
        public string C_PRODUCE_GROUP_NAME { get; set; }
        public Nullable<decimal> N_IF_EXEC_STATUS { get; set; }
        public string N_IF_EXEC_REMARK { get; set; }
        public Nullable<decimal> N_QUA_CASTOFF { get; set; }
        public Nullable<decimal> N_QUA_CUTTING { get; set; }
        public string C_EMP_ID { get; set; }
        public Nullable<decimal> N_QUA_SUCCESS { get; set; }
        public Nullable<decimal> N_PROD_WGT { get; set; }
        public Nullable<decimal> N_WARE_WGT { get; set; }
        public Nullable<decimal> N_WARE_OUT_WGT { get; set; }
        public Nullable<decimal> N_HG_WGT { get; set; }
        public Nullable<decimal> N_DP_WGT { get; set; }
        public Nullable<decimal> N_GP_WGT { get; set; }
        public Nullable<decimal> N_XY_WGT { get; set; }
        public Nullable<decimal> N_TW_WGT { get; set; }
        public Nullable<decimal> N_BHG_WGT { get; set; }
        public Nullable<decimal> N_HG_WGT_IN { get; set; }
        public Nullable<decimal> N_GP_WGT_IN { get; set; }
        public Nullable<decimal> N_XY_WGT_IN { get; set; }
        public Nullable<decimal> N_TW_WGT_IN { get; set; }
        public Nullable<decimal> N_BHG_WGT_IN { get; set; }
        public Nullable<decimal> N_HG_WGT_OUT { get; set; }
        public Nullable<decimal> N_GP_WGT_OUT { get; set; }
        public Nullable<decimal> N_XY_WGT_OUT { get; set; }
        public Nullable<decimal> N_TW_WGT_OUT { get; set; }
        public Nullable<decimal> N_BHG_WGT_OUT { get; set; }
        public Nullable<System.DateTime> D_SALE_TIME_MIN { get; set; }
        public Nullable<System.DateTime> D_SALE_TIME_MAX { get; set; }
        public Nullable<decimal> N_SLAB_XH_WGT { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public Nullable<System.DateTime> D_SWEEP_START { get; set; }
        public Nullable<System.DateTime> D_SWEEP_END { get; set; }
        public Nullable<short> N_IS_MERGE { get; set; }
    }
}
