//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_WGD_ITEM
    {
        public string C_ID { get; set; }
        public string C_MAIN_ID { get; set; }
        public string C_ROLL_WGD_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_SALE_AREA { get; set; }
        public string C_ZYX1 { get; set; }
        public string C_ZYX2 { get; set; }
        public string C_BZYQ { get; set; }
        public string C_MRSX { get; set; }
    }
}
