//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_PLAN_REGROUND
    {
        public string C_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<short> N_LEN { get; set; }
        public Nullable<short> N_QUA { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_XMGX { get; set; }
        public Nullable<short> N_TOTALSTEP { get; set; }
        public System.DateTime D_QR_DATE { get; set; }
        public Nullable<System.DateTime> D_Q_DATE { get; set; }
        public Nullable<short> N_QUA_VIRTUAL { get; set; }
        public string C_SLABWH_CODE { get; set; }
        public string C_SLABWH_AREA_CODE { get; set; }
        public string C_SLABWH_LOC_CODE { get; set; }
        public string C_SLABWH_TIER_CODE { get; set; }
        public string C_XMGX_GRD { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public Nullable<short> C_EXTEND1 { get; set; }
        public Nullable<short> C_EXTEND2 { get; set; }
        public Nullable<short> C_EXTEND3 { get; set; }
        public Nullable<short> C_EXTEND4 { get; set; }
        public Nullable<short> C_EXTEND5 { get; set; }
        public Nullable<short> C_EXTEND6 { get; set; }
        public Nullable<short> C_EXTEND7 { get; set; }
        public Nullable<short> C_EXTEND8 { get; set; }
        public Nullable<short> C_EXTEND9 { get; set; }
        public Nullable<short> C_EXTEND10 { get; set; }
        public Nullable<short> C_EXTEND11 { get; set; }
        public Nullable<short> C_EXTEND12 { get; set; }
        public Nullable<short> C_EXTEND13 { get; set; }
        public Nullable<short> C_EXTEND14 { get; set; }
        public Nullable<short> C_EXTEND15 { get; set; }
        public string C_EXTEND16 { get; set; }
        public string C_EXTEND17 { get; set; }
        public string C_EXTEND18 { get; set; }
        public string C_SLABWH_XLLOC_CODE { get; set; }
        public string C_EMP_CODE { get; set; }
    }
}
