//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_SPOT_CHECK
    {
        public string C_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_TICK_NO { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_ENTRUST_TYPE { get; set; }
        public string C_EMP_ID_ZY { get; set; }
        public Nullable<System.DateTime> D_MOD_DT_ZY { get; set; }
        public string C_EMP_ID_JS { get; set; }
        public Nullable<System.DateTime> D_MOD_DT_JS { get; set; }
    }
}
