//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_PLAN_REGROUND_HANDLER
    {
        public string C_ID { get; set; }
        public string C_REGROUND_ID { get; set; }
        public string C_REGROUND_ITEM_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public System.DateTime D_DT { get; set; }
        public string C_STA_ID { get; set; }
        public string C_XMBZ { get; set; }
        public Nullable<short> N_TOTAL_QUA { get; set; }
        public Nullable<short> N_QUA { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_REMARK { get; set; }
        public string C_QUALITY { get; set; }
        public string C_HW { get; set; }
        public string C_HG { get; set; }
        public string C_CAUSE { get; set; }
        public Nullable<short> N_NOT_QUA { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<short> N_STEP { get; set; }
        public string C_STEPNAME { get; set; }
        public string C_GRINDING_WHEEL { get; set; }
    }
}
