//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_SLABWH_LOG
    {
        public string C_ID { get; set; }
        public string C_SLAB_MAIN_ID { get; set; }
        public string C_MOVE_TYPE { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_SLABWH_CODE_BEFORE { get; set; }
        public string C_SLABWH_AREA_CODE_BEFORE { get; set; }
        public string C_SLABWH_LOC_CODE_BEFORE { get; set; }
        public string C_FLOOR_BEFORE { get; set; }
        public Nullable<System.DateTime> D_STORAGE_DT { get; set; }
        public string C_SLABWH_CODE_AFTER { get; set; }
        public string C_SLABWH_AREA_CODE_AFTER { get; set; }
        public string C_FLOOR_AFTER { get; set; }
        public string C_SALE_AREA { get; set; }
        public string C_TRANSPORTATION { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_SLABWH_LOC_CODE_AFTER { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public Nullable<System.DateTime> D_ESC_DATE { get; set; }
        public Nullable<System.DateTime> D_LSC_DATE { get; set; }
        public string C_COOLPIT_CODE { get; set; }
        public string C_COOLPIT_AREA_CODE { get; set; }
        public string C_COOLPIT_LOC_CODE { get; set; }
        public string C_COOLPIT { get; set; }
    }
}
