//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_STORAGE_LOG
    {
        public string C_ID { get; set; }
        public string C_TRC_ROLL_MAIN_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_TICK_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_MOVE_TYPE { get; set; }
        public string C_SPEC { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_LINEWH_CODE_BEFORE { get; set; }
        public string C_LINEWH_AREA_CODE_BEFORE { get; set; }
        public string C_LINEWH_LOC_CODE_BEFORE { get; set; }
        public string C_FLOOR_BEFORE { get; set; }
        public Nullable<System.DateTime> D_STORAGE_DT { get; set; }
        public string C_LINEWH_CODE_AFTER { get; set; }
        public string C_LINEWH_AREA_CODE_AFTER { get; set; }
        public string C_LINEWH_LOC_CODE_AFTER { get; set; }
        public string C_FLOOR_AFTER { get; set; }
        public string C_SALE_AREA { get; set; }
        public string C_TRANSPORTATION { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public decimal N_STATUS { get; set; }
    }
}
