//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_COGDOWN_PRODUCT
    {
        public string C_ID { get; set; }
        public string C_COGDOWN_ID { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_ORD_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_STA_ID { get; set; }
        public string C_STA_CODE { get; set; }
        public string C_STA_DESC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STL_GRD_PRE { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<decimal> N_LEN { get; set; }
        public Nullable<short> N_QUA { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public string D_CCM_DATE { get; set; }
        public string C_CCM_SHIFT { get; set; }
        public string C_CCM_GROUP { get; set; }
        public string C_CCM_EMP_ID { get; set; }
        public string C_MOVE_TYPE { get; set; }
        public string C_SC_STATE { get; set; }
        public Nullable<System.DateTime> D_ESC_DATE { get; set; }
        public Nullable<System.DateTime> D_LSC_DATE { get; set; }
        public string C_QKP_STATE { get; set; }
        public string C_KP_ID { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CUS_NO { get; set; }
        public string C_CUS_NAME { get; set; }
        public Nullable<System.DateTime> D_WL_DATE { get; set; }
        public string C_WL_SHIFT { get; set; }
        public string C_WL_GROUP { get; set; }
        public string C_WL_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_WE_DATE { get; set; }
        public string C_WE_SHIFT { get; set; }
        public string C_WE_GROUP { get; set; }
        public string C_WE_EMP_ID { get; set; }
        public string C_STOCK_STATE { get; set; }
        public string C_MAT_TYPE { get; set; }
        public string C_QGP_STATE { get; set; }
        public string C_SLABWH_CODE { get; set; }
        public string C_SLABWH_AREA_CODE { get; set; }
        public string C_SLABWH_LOC_CODE { get; set; }
        public string C_SLABWH_TIER_CODE { get; set; }
        public Nullable<short> N_WGT_METER { get; set; }
        public string C_QF_NAME { get; set; }
        public string C_DESIGN_NO { get; set; }
        public string C_ZRBM { get; set; }
        public string C_IS_DEPOT { get; set; }
        public string C_ISXM { get; set; }
        public string C_XMGX { get; set; }
        public string C_ISFREE { get; set; }
        public string C_JUDGE_LEV_CF { get; set; }
        public string C_JUDGE_LEV_XN { get; set; }
        public string C_JUDGE_LEV_ZH { get; set; }
        public string C_JUDGE_LEV_ZH_PEOPLE { get; set; }
        public Nullable<System.DateTime> D_JUDGE_DATE { get; set; }
        public string C_IS_QR { get; set; }
        public string C_QR_USER { get; set; }
        public Nullable<System.DateTime> D_QR_DATE { get; set; }
        public Nullable<System.DateTime> D_Q_DATE { get; set; }
        public string C_SCUTCHEON { get; set; }
        public string C_GP_TYPE { get; set; }
        public string C_REMARK { get; set; }
        public Nullable<System.DateTime> D_START_DATE { get; set; }
        public Nullable<System.DateTime> D_END_DATE { get; set; }
        public string C_COGDOWN_SHIFT { get; set; }
        public string C_COGDOWN_GROUP { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_COG_STA_ID { get; set; }
        public string C_MOVE_SHIFT { get; set; }
        public string C_MOVE_GROUP { get; set; }
        public string C_MOVE_ID { get; set; }
        public Nullable<System.DateTime> C_MOVE_START { get; set; }
        public Nullable<System.DateTime> C_MOVE_END { get; set; }
        public Nullable<decimal> N_IF_EXEC_STATUS { get; set; }
        public string N_IF_EXEC_REMARK { get; set; }
        public string C_ZYX1 { get; set; }
        public string C_ZYX2 { get; set; }
        public string C_EXTEND1 { get; set; }
        public string C_EXTEND2 { get; set; }
        public string C_EXTEND3 { get; set; }
        public string C_EXTEND4 { get; set; }
        public string C_EXTEND5 { get; set; }
        public string C_EXTEND6 { get; set; }
        public string C_EXTEND7 { get; set; }
        public string C_EXTEND8 { get; set; }
        public string C_EXTEND9 { get; set; }
        public string C_EXTEND10 { get; set; }
    }
}
