//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLLCZ_LOG
    {
        public string C_ID { get; set; }
        public string C_DH { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_TICK_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SPEC { get; set; }
        public string C_JUDGE_LEV_BP { get; set; }
        public string C_LINEWH_CODE { get; set; }
        public string C_LINEWH_AREA_CODE { get; set; }
        public string C_LINEWH_LOC_CODE { get; set; }
        public string C_YLINEWH_CODE { get; set; }
        public string C_YLINEWH_AREA_CODE { get; set; }
        public string C_YLINEWH_LOC_CODE { get; set; }
        public string C_JUDGE_LEV_ZH { get; set; }
        public Nullable<System.DateTime> D_CZ_DATE { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_BARCODE { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_BZYQ { get; set; }
        public string C_ZHJL { get; set; }
    }
}
