//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_WW_MAIN
    {
        public string C_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_PLANT { get; set; }
        public string C_ORD_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public Nullable<decimal> N_QUA_TOTAL { get; set; }
        public Nullable<decimal> N_WGT_TOTAL { get; set; }
        public string C_STL_GRD_SLAB { get; set; }
        public string C_SPEC_SLAB { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_QUA_REMOVE { get; set; }
        public Nullable<decimal> N_WGT_REMOVE { get; set; }
        public string C_MAT_SLAB_CODE { get; set; }
        public string C_MAT_SLAB_NAME { get; set; }
        public string C_REMARK { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE_B { get; set; }
        public string C_PRODUCE_EMP_ID { get; set; }
        public string C_PRODUCE_SHIFT { get; set; }
        public string C_PRODUCE_GROUP { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE_E { get; set; }
        public string C_MAT_XC_CODE { get; set; }
        public string C_MAT_XC_NAME { get; set; }
        public string C_XC_BATCH_NO { get; set; }
        public string C_XC_LINEWH_CODE { get; set; }
        public string C_CHECKSTATE_NAME { get; set; }
        public string C_LINEWH_NAME { get; set; }
        public string C_LINEWH_CODE { get; set; }
        public string C_XC_BZYQ { get; set; }
        public string C_BZYQ { get; set; }
    }
}
