//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_MAIN
    {
        public string C_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_PLANT { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_PLAN_ID { get; set; }
        public Nullable<decimal> N_QUA_TOTAL { get; set; }
        public Nullable<decimal> N_WGT_TOTAL { get; set; }
        public string C_STL_GRD_SLAB { get; set; }
        public string C_SPEC_SLAB { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<decimal> N_QUA_REMOVE { get; set; }
        public Nullable<decimal> N_WGT_REMOVE { get; set; }
        public Nullable<decimal> N_QUA_RETRUN { get; set; }
        public Nullable<decimal> N_WGT_RETRUN { get; set; }
        public Nullable<decimal> N_QUA_JOIN { get; set; }
        public Nullable<decimal> N_WGT_JOIN { get; set; }
        public Nullable<decimal> N_QUA_EXIT { get; set; }
        public Nullable<decimal> N_WGT_EXIT { get; set; }
        public Nullable<decimal> N_QUA_CPHALF { get; set; }
        public Nullable<decimal> N_WGT_HALF { get; set; }
        public Nullable<decimal> N_QUA_CPWHOLE { get; set; }
        public Nullable<decimal> N_WGT_CPWHOLE { get; set; }
        public decimal C_ROLL_STATE { get; set; }
        public string C_FUR_TYPE { get; set; }
        public Nullable<decimal> N_QUA_ELIM { get; set; }
        public Nullable<decimal> N_WGT_ELIM { get; set; }
        public string C_MAT_SLAB_CODE { get; set; }
        public string C_MAT_SLAB_NAME { get; set; }
        public string C_REMARK { get; set; }
        public decimal N_STATUS { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_SLAB_NUM { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE_B { get; set; }
        public string C_PRODUCE_EMP_ID { get; set; }
        public string C_PRODUCE_SHIFT { get; set; }
        public string C_PRODUCE_GROUP { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE_E { get; set; }
        public Nullable<decimal> N_QUA_TOTAL_VIRTUAL { get; set; }
        public Nullable<decimal> N_WGT_TOTAL_VIRTUAL { get; set; }
        public Nullable<decimal> N_PROD_WGT { get; set; }
        public Nullable<decimal> N_WARE_WGT { get; set; }
        public Nullable<decimal> N_WARE_OUT_WGT { get; set; }
        public Nullable<short> N_IS_MERGE { get; set; }
        public Nullable<System.DateTime> D_P_START_TIME { get; set; }
        public Nullable<System.DateTime> D_P_END_TIME { get; set; }
        public string C_STD_CODE_SLAB { get; set; }
    }
}
