//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRC_ROLL_PRODCUT
    {
        public string C_ID { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_TRC_ROLL_MAIN_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_TICK_NO { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STL_GRD_BEFORE { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_STD_CODE_BEFORE { get; set; }
        public string C_MOVE_TYPE { get; set; }
        public string C_SPEC { get; set; }
        public string C_SHIFT { get; set; }
        public string C_GROUP { get; set; }
        public string C_STA_ID { get; set; }
        public string C_JUDGE_LEV_BP { get; set; }
        public string C_DP_SHIFT { get; set; }
        public string C_DP_GROUP { get; set; }
        public string C_DP_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_DP_DT { get; set; }
        public string C_PLANT_ID { get; set; }
        public string C_PLANT_DESC { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_CODE_BEFORE { get; set; }
        public string C_MAT_DESC { get; set; }
        public string C_MAT_DESC_BEFORE { get; set; }
        public string C_IS_DEPOT { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_ISFREE { get; set; }
        public string C_LINEWH_CODE { get; set; }
        public string C_LINEWH_AREA_CODE { get; set; }
        public string C_LINEWH_LOC_CODE { get; set; }
        public string C_FLOOR { get; set; }
        public string C_CUST_AREA { get; set; }
        public string C_SALE_AREA { get; set; }
        public string C_JUDGE_LEV_CF { get; set; }
        public string C_JUDGE_LEV_XN { get; set; }
        public string C_JUDGE_LEV_XN_RE { get; set; }
        public string C_JUDGE_LEV_ZH_PEOPLE { get; set; }
        public Nullable<System.DateTime> D_JUDGE_DATE { get; set; }
        public string C_IS_QR { get; set; }
        public string C_QR_USER { get; set; }
        public Nullable<System.DateTime> D_QR_DATE { get; set; }
        public string C_DESIGN_NO { get; set; }
        public string C_JUDGE_LEV_ZH { get; set; }
        public string C_IS_TB { get; set; }
        public string C_SCUTCHEON { get; set; }
        public string C_GP_TYPE { get; set; }
        public string C_BARCODE { get; set; }
        public string C_RKDH { get; set; }
        public string C_FYDH { get; set; }
        public string C_CKDH { get; set; }
        public string C_MOVE_DESC { get; set; }
        public string C_CKRY { get; set; }
        public Nullable<System.DateTime> D_CKRQ { get; set; }
        public string C_RKRY { get; set; }
        public Nullable<System.DateTime> D_RKRQ { get; set; }
        public string C_BZYQ { get; set; }
        public Nullable<System.DateTime> D_WEIGHT_DT { get; set; }
        public Nullable<System.DateTime> D_PRODUCE_DATE { get; set; }
        public string C_ZYX1 { get; set; }
        public string C_ZYX2 { get; set; }
        public string C_ZKD_NO { get; set; }
        public string C_QTCKD_NO { get; set; }
        public string C_MASTER_ID { get; set; }
        public string C_GP_BEFORE_ID { get; set; }
        public string C_GP_AFTER_ID { get; set; }
        public string C_REASON_NAME { get; set; }
        public string C_IS_PD { get; set; }
        public string C_ORDER_NO1 { get; set; }
        public string C_WWBATCH_NO { get; set; }
        public string C_FRFLAG { get; set; }
        public Nullable<short> N_SFOB { get; set; }
        public string C_STL_GRD_TYPE { get; set; }
        public string C_SFJK { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_PCINFO { get; set; }
        public string C_SCRQ { get; set; }
        public string C_QGP_STATE { get; set; }
        public string C_COMMUTE_REASON { get; set; }
        public short N_QUA { get; set; }
        public string C_DEPOT_TYPE { get; set; }
        public string C_TYPE { get; set; }
        public System.DateTime D_INSERT_TIME { get; set; }
    }
}
