//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_SNKC
    {
        public string C_ID { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_BZYQ { get; set; }
        public string C_LINEWH_CODE1 { get; set; }
        public Nullable<decimal> N_WGT1 { get; set; }
        public string C_LINEWH_CODE2 { get; set; }
        public Nullable<decimal> N_WGT2 { get; set; }
        public string C_LINEWH_CODE3 { get; set; }
        public Nullable<decimal> N_WGT3 { get; set; }
        public string C_LINEWH_CODE4 { get; set; }
        public Nullable<decimal> N_WGT4 { get; set; }
        public string C_LINEWH_CODE5 { get; set; }
        public Nullable<decimal> N_WGT5 { get; set; }
        public string C_LINEWH_CODE6 { get; set; }
        public Nullable<decimal> N_WGT6 { get; set; }
        public string C_LINEWH_CODE7 { get; set; }
        public Nullable<decimal> N_WGT7 { get; set; }
        public string C_LINEWH_CODE8 { get; set; }
        public Nullable<decimal> N_WGT8 { get; set; }
        public string C_LINEWH_CODE9 { get; set; }
        public Nullable<decimal> N_WGT9 { get; set; }
        public string C_LINEWH_CODE10 { get; set; }
        public Nullable<decimal> N_WGT10 { get; set; }
    }
}
