//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_GPRPKBB
    {
        public string C_ID { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_TYPE { get; set; }
        public string N_SOFT { get; set; }
        public string C_STL_GRD { get; set; }
        public Nullable<decimal> N_YCWGT { get; set; }
        public Nullable<decimal> N_DRWGT { get; set; }
        public Nullable<decimal> N_DRSCWGT { get; set; }
        public Nullable<decimal> N_YSCWGT { get; set; }
        public Nullable<decimal> N_DRXHWGT { get; set; }
        public Nullable<decimal> N_YXHWGT { get; set; }
    }
}
