//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_ROLL_CQ
    {
        public string C_ID { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public Nullable<decimal> N_QUA { get; set; }
        public string C_TYPE { get; set; }
        public Nullable<decimal> N_DAY { get; set; }
        public Nullable<decimal> N_MIN_OVERDAY { get; set; }
        public Nullable<decimal> N_MAX_OVERDAY { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public Nullable<decimal> N_CQ_WGT { get; set; }
        public Nullable<decimal> N_CQ_QUA { get; set; }
        public System.DateTime D_DT { get; set; }
    }
}
