//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_GPDRKC_INFO
    {
        public string C_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public short N_NUM { get; set; }
        public decimal N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<System.DateTime> D_CCM_DATE { get; set; }
        public string C_JUDGE_LEV_ZH { get; set; }
        public string C_MAT_TYPE { get; set; }
        public string C_SLABWH_CODE { get; set; }
        public string C_ZYX1 { get; set; }
        public string C_ZYX2 { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public string C_TYPE { get; set; }
    }
}
