//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRP_PLAN_COGDOWN
    {
        public string C_ID { get; set; }
        public short N_STATUS { get; set; }
        public string C_INITIALIZE_ITEM_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public decimal N_WGT { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_TECH_PROT { get; set; }
        public string C_SPEC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STD_CODE { get; set; }
        public Nullable<short> N_USER_LEV { get; set; }
        public Nullable<short> N_STL_GRD_LEV { get; set; }
        public Nullable<short> N_ORDER_LEV { get; set; }
        public string C_QUALIRY_LEV { get; set; }
        public Nullable<System.DateTime> D_NEED_DT { get; set; }
        public Nullable<System.DateTime> D_DELIVERY_DT { get; set; }
        public Nullable<System.DateTime> D_DT { get; set; }
        public string C_LINE_DESC { get; set; }
        public string C_LINE_CODE { get; set; }
        public Nullable<System.DateTime> D_P_START_TIME { get; set; }
        public Nullable<System.DateTime> D_P_END_TIME { get; set; }
        public Nullable<short> N_PROD_TIME { get; set; }
        public Nullable<short> N_SORT { get; set; }
        public Nullable<decimal> N_ROLL_PROD_WGT { get; set; }
        public string C_ROLL_PROD_EMP_ID { get; set; }
        public string C_STL_ROL_DT { get; set; }
        public Nullable<decimal> N_PROD_WGT { get; set; }
        public Nullable<decimal> N_WARE_WGT { get; set; }
        public Nullable<decimal> N_WARE_OUT_WGT { get; set; }
        public Nullable<short> N_FLAG { get; set; }
        public Nullable<decimal> N_ISSUE_WGT { get; set; }
        public string C_CUST_NO { get; set; }
        public string C_CUST_NAME { get; set; }
        public string C_SALE_CHANNEL { get; set; }
        public string C_PACK { get; set; }
        public string C_DESIGN_NO { get; set; }
        public decimal N_GROUP_WGT { get; set; }
        public string C_STA_ID { get; set; }
        public Nullable<System.DateTime> D_START_TIME { get; set; }
        public Nullable<System.DateTime> D_END_TIME { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public Nullable<short> N_ROLL_WGT { get; set; }
        public Nullable<decimal> N_MACH_WGT { get; set; }
        public string C_CAST_NO { get; set; }
        public string C_INITIALIZE_ID { get; set; }
        public short N_UPLOADSTATUS { get; set; }
        public string C_FREE1 { get; set; }
        public string C_FREE2 { get; set; }
        public Nullable<decimal> N_PW { get; set; }
        public Nullable<long> N_LENTH { get; set; }
        public string C_MATRL_CODE_SLAB { get; set; }
        public string C_MATRL_NAME_SLAB { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public Nullable<long> N_SLAB_LENGTH { get; set; }
        public Nullable<decimal> N_SLAB_PW { get; set; }
    }
}
