//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_CUSTFILE
    {
        public string C_ID { get; set; }
        public string C_NC_ID { get; set; }
        public string C_NC_M_ID { get; set; }
        public Nullable<short> N_ISFLAG { get; set; }
        public string C_NO { get; set; }
        public string C_NAME { get; set; }
        public string C_SHORNAME { get; set; }
        public string C_AREATYPE { get; set; }
        public string C_LEGALREPRES { get; set; }
        public string C_AGENT { get; set; }
        public string C_OPERATOR { get; set; }
        public string C_FAX { get; set; }
        public string C_TAXPAYERNO { get; set; }
        public Nullable<short> N_LEVEL { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public Nullable<short> N_ISGPS { get; set; }
        public string C_AREAMMAX { get; set; }
        public string C_EXTEND1 { get; set; }
        public string C_EXTEND2 { get; set; }
        public string C_EXTEND3 { get; set; }
        public string C_EXTEND4 { get; set; }
        public string C_EXTEND5 { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
    }
}
