//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_DIC
    {
        public string C_ID { get; set; }
        public string C_TYPECODE { get; set; }
        public string C_TYPENAME { get; set; }
        public string C_DETAILCODE { get; set; }
        public string C_DETAILNAME { get; set; }
        public Nullable<short> C_INDEX { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public Nullable<short> N_ISGPS { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_EXTEND1 { get; set; }
        public string C_EXTEND2 { get; set; }
        public string C_EXTEND3 { get; set; }
        public string C_EXTEND4 { get; set; }
        public string C_EXTEND5 { get; set; }
    }
}
