//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_MODULE
    {
        public string C_MODULEID { get; set; }
        public string C_PARENTMODULEID { get; set; }
        public string C_MODULENAME { get; set; }
        public string C_ASSEMBLYNAME { get; set; }
        public string C_MODULECLASS { get; set; }
        public string C_DISABLE { get; set; }
        public Nullable<short> N_ORDER { get; set; }
        public Nullable<short> N_IMAGEINDEX { get; set; }
        public string C_MODULE_TYPE { get; set; }
        public string C_QUERY_STR { get; set; }
        public string C_REMARK { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
