//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ROLE_FUN_PCI
    {
        public string C_ID { get; set; }
        public string C_MODULE_ID { get; set; }
        public string C_ROLE_ID { get; set; }
        public string C_FUNCTION_TYPE { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
    }
}
