//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_SOFT_VERSION
    {
        public string C_ID { get; set; }
        public string C_CP_IP { get; set; }
        public string C_CP_NAME { get; set; }
        public string C_VERSION { get; set; }
        public System.DateTime D_UPLOAD_TIME { get; set; }
    }
}
