//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_SERVER_CONFIG
    {
        public string C_ID { get; set; }
        public string C_URL { get; set; }
        public string C_FILE { get; set; }
        public string C_USERNAME { get; set; }
        public string C_PASSWORD { get; set; }
        public string C_TYPE { get; set; }
        public string C_USE { get; set; }
        public string C_REMARK { get; set; }
        public string C_NO { get; set; }
    }
}
