//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_USER
    {
        public string C_ID { get; set; }
        public string C_NAME { get; set; }
        public string C_ACCOUNT { get; set; }
        public string C_PASSWORD { get; set; }
        public string C_EMAIL { get; set; }
        public string C_MOBILE { get; set; }
        public Nullable<short> N_TYPE { get; set; }
        public Nullable<short> N_STATUS { get; set; }
        public string C_DESC { get; set; }
        public Nullable<System.DateTime> D_LASTLOGINTIME { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_EMP_NAME { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_MOBILE2 { get; set; }
        public string C_PHONE { get; set; }
        public string C_SHORTNAME { get; set; }
        public string C_CUST_ID { get; set; }
        public string C_TOKEN_ID { get; set; }
        public string C_CJNAME { get; set; }
        public string C_CJINTRO { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_LEGALREPRES { get; set; }
        public string C_CGJCR { get; set; }
        public string C_JOB { get; set; }
        public string C_JCTEL { get; set; }
        public string C_ADDRESS { get; set; }
        public string C_AREA { get; set; }
        public string C_MANAGER { get; set; }
    }
}
