//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC_SLAB_MES
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string MATERIALID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string POSITION { get; set; }
        public Nullable<int> QASTATUS { get; set; }
        public Nullable<int> QALEVEL { get; set; }
        public string ORDERCONTRACTID { get; set; }
        public string PRODUCECONTRACTID { get; set; }
        public string SALESCONTRACTID { get; set; }
        public string CASTERID { get; set; }
        public string CASTING_NO { get; set; }
        public Nullable<int> CASTING_HEAT_CNT { get; set; }
        public string PRE_STEELGRADEINDEX { get; set; }
        public string STEELGRADEINDEX { get; set; }
        public string CUT_STEELGRADEINDEX { get; set; }
        public string FINAL_STEELGRADEINDEX { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> THICKNESS { get; set; }
        public string CUR_SECTION_ID { get; set; }
        public string CUR_PILE_ID { get; set; }
        public string CUR_LAYER_ID { get; set; }
        public Nullable<int> CUR_SEQ_ID { get; set; }
        public string CUR_BAY_ID { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<int> HOT_SEND_FLAG { get; set; }
        public Nullable<int> PROCESS_TYPE { get; set; }
        public string PLAN_ORD_ID { get; set; }
        public Nullable<System.DateTime> PRODUCE_DATE { get; set; }
        public Nullable<int> FINISH_FLAG { get; set; }
        public Nullable<System.DateTime> FINISHEDTIME { get; set; }
        public Nullable<int> BLOOM_COUNT { get; set; }
        public Nullable<decimal> CAL_WEIGHT { get; set; }
        public Nullable<int> RIGHT_COUNT { get; set; }
        public Nullable<decimal> RIGHT_WEIGHT { get; set; }
        public Nullable<decimal> WASTER_COUNT { get; set; }
        public Nullable<decimal> WASTER_WEIGHT { get; set; }
        public Nullable<decimal> WASTER_COUNT1 { get; set; }
        public Nullable<decimal> WASTER_WEIGHT1 { get; set; }
        public string WASTER_REASON1 { get; set; }
        public Nullable<decimal> WASTER_COUNT2 { get; set; }
        public Nullable<decimal> WASTER_WEIGHT2 { get; set; }
        public string WASTER_REASON2 { get; set; }
        public Nullable<decimal> WASTER_COUNT3 { get; set; }
        public Nullable<decimal> WASTER_WEIGHT3 { get; set; }
        public string WASTER_REASON3 { get; set; }
        public Nullable<int> WRONG_COUNT { get; set; }
        public Nullable<decimal> WRONG_WEIGHT { get; set; }
        public Nullable<int> WRONG_COUNT1 { get; set; }
        public Nullable<decimal> WRONG_WEIGHT1 { get; set; }
        public string WRONG_REASON1 { get; set; }
        public Nullable<int> WRONG_COUNT2 { get; set; }
        public Nullable<decimal> WRONG_WEIGHT2 { get; set; }
        public string WRONG_REASON2 { get; set; }
        public Nullable<int> WRONG_COUNT3 { get; set; }
        public Nullable<decimal> WRONG_WEIGHT3 { get; set; }
        public string WRONG_REASON3 { get; set; }
        public string SUFACEDEFACTDES { get; set; }
        public string REASON { get; set; }
        public string HEATID { get; set; }
        public Nullable<int> TEST_ROLL_COUNT { get; set; }
        public Nullable<decimal> TEST_ROLL_WEIGHT { get; set; }
        public Nullable<int> BACK_FLAG { get; set; }
        public Nullable<System.DateTime> BACK_DATE { get; set; }
        public Nullable<int> ADD_BLOOM_COUNT { get; set; }
        public Nullable<int> DIV_BLOOM_COUNT { get; set; }
        public Nullable<int> PLAN_BLOOM_COUNT { get; set; }
        public string ADD_DIV_HEATID { get; set; }
        public string ADD_HEATID1 { get; set; }
        public string ADD_HEATID2 { get; set; }
        public Nullable<int> ADD_BLOOM_COUNT2 { get; set; }
        public System.DateTime D_INSERT_TIME { get; set; }
        public string C_UP_STATE { get; set; }
    }
}
