//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC_STOVE_TIME
    {
        public string PREHEATID { get; set; }
        public string HEATID { get; set; }
        public string LF_TREATNO { get; set; }
        public string RH_TREATNO { get; set; }
        public string CASTER_TREATNO { get; set; }
        public Nullable<System.DateTime> ACT_TIME_IRONPREPARED { get; set; }
        public Nullable<System.DateTime> ACT_TIME_BOFSTART { get; set; }
        public Nullable<System.DateTime> ACT_TIME_BOFTAPPED { get; set; }
        public Nullable<System.DateTime> ACT_TIME_TAPPEDSIDEEND { get; set; }
        public Nullable<System.DateTime> ACT_TIME_LFARRIVAL { get; set; }
        public Nullable<System.DateTime> ACT_TIME_LFSTART { get; set; }
        public Nullable<System.DateTime> ACT_TIME_LFEND { get; set; }
        public Nullable<System.DateTime> ACT_TIME_LFLEAVE { get; set; }
        public Nullable<System.DateTime> ACT_TIME_RHARRIVAL { get; set; }
        public Nullable<System.DateTime> ACT_TIME_RHSTART { get; set; }
        public Nullable<System.DateTime> ACT_TIME_RHEND { get; set; }
        public Nullable<System.DateTime> ACT_TIME_RHLEAVE { get; set; }
        public Nullable<System.DateTime> ACT_TIME_CASTERARRIVAL { get; set; }
        public Nullable<System.DateTime> ACT_TIME_CASTINGSTART { get; set; }
        public Nullable<System.DateTime> ACT_TIME_CASTINGEND { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string C_ZL_ID { get; set; }
        public string C_ZL_CODE { get; set; }
        public string C_ZL_DESC { get; set; }
        public string C_LF_ID { get; set; }
        public string C_LF_CODE { get; set; }
        public string C_LF_DESC { get; set; }
        public string C_RH_ID { get; set; }
        public string C_RH_CODE { get; set; }
        public string C_RH_DESC { get; set; }
        public string C_CC_ID { get; set; }
        public string C_CC_CODE { get; set; }
        public string C_CC_DESC { get; set; }
        public string C_PLAN_SMS_ID { get; set; }
    }
}
