//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC_SLAB_MOVE
    {
        public string C_ID { get; set; }
        public string C_MOVE_TYPE { get; set; }
        public string C_SLAB_MAIN_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_STOVE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<long> N_LEN { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public Nullable<decimal> N_WGT { get; set; }
        public string C_STOCK_CODE { get; set; }
        public string C_STOCK_CODE_TO { get; set; }
        public string C_AREA_CODE { get; set; }
        public string C_KW_CODE { get; set; }
        public string C_FLOOD_CODE { get; set; }
        public short N_QUA { get; set; }
        public Nullable<System.DateTime> D_MOVE_DATE { get; set; }
        public string C_MOVE_GROUP { get; set; }
        public string C_MOVE_SHIFT { get; set; }
        public string C_MOVE_EMP_ID { get; set; }
        public short N_STATUS { get; set; }
        public string C_REMARK { get; set; }
        public string C_ZKDH { get; set; }
        public string C_ZKDHID { get; set; }
        public string C_BATCH_NO { get; set; }
    }
}
