//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC_ALLOT_LOG
    {
        public string C_ID { get; set; }
        public string C_SLAB_MAIN_ID { get; set; }
        public Nullable<decimal> N_TYPE { get; set; }
        public Nullable<System.DateTime> D_MOD_DT { get; set; }
        public string C_EMP_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_SLABWH_CODE { get; set; }
        public string C_SLABWH_AREA_CODE { get; set; }
        public string C_SLABWH_LOC_CODE { get; set; }
        public string C_SLABWH_TIER_CODE { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string N_LEN { get; set; }
        public string C_STOVE { get; set; }
    }
}
