//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC_SLAB_MAIN
    {
        public string C_ID { get; set; }
        public string C_PLAN_ID { get; set; }
        public string C_BATCH_NO { get; set; }
        public string C_ORD_NO { get; set; }
        public string C_STOVE { get; set; }
        public string C_STA_ID { get; set; }
        public string C_STA_CODE { get; set; }
        public string C_STA_DESC { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_STL_GRD_PRE { get; set; }
        public string C_MAT_CODE { get; set; }
        public string C_MAT_NAME { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<short> N_LEN { get; set; }
        public short N_QUA { get; set; }
        public decimal N_WGT { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public Nullable<System.DateTime> D_CCM_DATE { get; set; }
        public string C_CCM_SHIFT { get; set; }
        public string C_CCM_GROUP { get; set; }
        public string C_CCM_EMP_ID { get; set; }
        public string C_MOVE_TYPE { get; set; }
        public string C_SC_STATE { get; set; }
        public Nullable<System.DateTime> D_ESC_DATE { get; set; }
        public Nullable<System.DateTime> D_LSC_DATE { get; set; }
        public string C_QKP_STATE { get; set; }
        public string C_KP_ID { get; set; }
        public string C_CON_NO { get; set; }
        public string C_CUS_NO { get; set; }
        public string C_CUS_NAME { get; set; }
        public Nullable<System.DateTime> D_WL_DATE { get; set; }
        public string C_WL_SHIFT { get; set; }
        public string C_WL_GROUP { get; set; }
        public string C_WL_EMP_ID { get; set; }
        public Nullable<System.DateTime> D_WE_DATE { get; set; }
        public string C_WE_SHIFT { get; set; }
        public string C_WE_GROUP { get; set; }
        public string C_WE_EMP_ID { get; set; }
        public string C_STOCK_STATE { get; set; }
        public string C_MAT_TYPE { get; set; }
        public string C_QGP_STATE { get; set; }
        public string C_SLABWH_CODE { get; set; }
        public string C_SLABWH_AREA_CODE { get; set; }
        public string C_SLABWH_LOC_CODE { get; set; }
        public string C_SLABWH_TIER_CODE { get; set; }
        public Nullable<short> N_WGT_METER { get; set; }
        public string C_QF_NAME { get; set; }
        public string C_DESIGN_NO { get; set; }
        public string C_ZRBM { get; set; }
        public string C_IS_DEPOT { get; set; }
        public string C_ISXM { get; set; }
        public string C_XMGX { get; set; }
        public string C_ISFREE { get; set; }
        public string C_JUDGE_LEV_CF { get; set; }
        public string C_JUDGE_LEV_XN { get; set; }
        public string C_JUDGE_LEV_ZH { get; set; }
        public string C_JUDGE_LEV_ZH_PEOPLE { get; set; }
        public Nullable<System.DateTime> D_JUDGE_DATE { get; set; }
        public string C_IS_QR { get; set; }
        public string C_QR_USER { get; set; }
        public Nullable<System.DateTime> D_QR_DATE { get; set; }
        public Nullable<System.DateTime> D_Q_DATE { get; set; }
        public string C_SCUTCHEON { get; set; }
        public string C_GP_TYPE { get; set; }
        public string C_REMARK { get; set; }
        public string C_IS_TB { get; set; }
        public string C_MASTER_ID { get; set; }
        public string C_GP_BEFORE_ID { get; set; }
        public string C_GP_AFTER_ID { get; set; }
        public Nullable<System.DateTime> D_STACK_DATE { get; set; }
        public string C_STACK_USER { get; set; }
        public string C_STACK_SHIFT { get; set; }
        public string C_STACK_GROUP { get; set; }
        public string C_IS_PD { get; set; }
        public string C_REASON_NAME { get; set; }
        public string C_FYDH { get; set; }
        public string C_SLAB_STATUS { get; set; }
        public string C_ZKDH { get; set; }
        public string C_ZKDHID { get; set; }
        public string C_LGJH { get; set; }
        public string C_MES_FLOOR { get; set; }
        public Nullable<decimal> N_JZ { get; set; }
        public string C_HL { get; set; }
        public Nullable<long> N_HL_TIME { get; set; }
        public string C_HLYQ { get; set; }
        public string C_DFP_HL { get; set; }
        public int N_DFP_HL_TIME { get; set; }
        public string C_ROUTE { get; set; }
        public string C_ZYX1 { get; set; }
        public string C_ZYX2 { get; set; }
        public string C_FRFLAG { get; set; }
        public string C_FYID { get; set; }
        public string C_COMMUTE_REASON { get; set; }
        public string C_DEPOT_TYPE { get; set; }
        public string C_MATRL_CODE_KP { get; set; }
        public string C_MATRL_NAME_KP { get; set; }
        public string C_KP_SIZE { get; set; }
        public Nullable<long> N_KP_LENGTH { get; set; }
        public Nullable<decimal> N_KP_PW { get; set; }
        public string C_TYPE { get; set; }
        public string C_SLAB_TYPE_R { get; set; }
    }
}
