//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC_SLAB_MAIN_KP
    {
        public string C_ID { get; set; }
        public string C_SLAN_PLAN_KP_ID { get; set; }
        public string C_STA_ID { get; set; }
        public string C_SPEC { get; set; }
        public Nullable<short> N_LEN { get; set; }
        public Nullable<short> N_QUA { get; set; }
        public Nullable<short> N_WGT { get; set; }
        public string D_ACT_START_TIME { get; set; }
        public string D_ACT_END_TIME { get; set; }
        public Nullable<short> N_BFZS { get; set; }
        public Nullable<short> N_KPSJ { get; set; }
        public string C_BC { get; set; }
        public string C_BZ { get; set; }
        public short N_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_REMARK { get; set; }
    }
}
