//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSP_PLAN_SMS
    {
        public string C_ID { get; set; }
        public string C_ORDER_NO { get; set; }
        public string C_DESIGN_NO { get; set; }
        public Nullable<decimal> N_SLAB_WGT { get; set; }
        public string C_CTRL_NO { get; set; }
        public string C_CCM_ID { get; set; }
        public string C_CCM_DESC { get; set; }
        public string C_PROD_NAME { get; set; }
        public string C_STL_GRD { get; set; }
        public string C_SPEC_CODE { get; set; }
        public string C_LENGTH { get; set; }
        public string C_MATRL_NO { get; set; }
        public string C_MATRL_NAME { get; set; }
        public string C_SLAB_SIZE { get; set; }
        public string C_SLAB_LENGTH { get; set; }
        public string C_STATE { get; set; }
        public string C_STD_CODE { get; set; }
        public string C_INITIALIZE_ITEM_ID { get; set; }
        public Nullable<System.DateTime> D_P_START_TIME { get; set; }
        public Nullable<System.DateTime> D_P_END_TIME { get; set; }
        public Nullable<decimal> N_PROD_TIME { get; set; }
        public Nullable<decimal> N_SORT { get; set; }
        public string C_CAST_NO { get; set; }
        public short N_STATUS { get; set; }
        public string C_EMP_ID { get; set; }
        public System.DateTime D_MOD_DT { get; set; }
        public string C_REMARK { get; set; }
        public short N_CREAT_PLAN { get; set; }
        public short N_CREAT_ZG_PLAN { get; set; }
        public decimal N_PRODUCE_TIME { get; set; }
        public string C_ZL_ID { get; set; }
        public string C_LF_ID { get; set; }
        public string C_RH_ID { get; set; }
        public string C_LGJH { get; set; }
        public string C_QUA { get; set; }
        public Nullable<System.DateTime> D_ARRIVE_ZG_TIME { get; set; }
        public string C_BY1 { get; set; }
        public string C_BY2 { get; set; }
        public string C_BY3 { get; set; }
        public string C_RH { get; set; }
        public string C_DFP_HL { get; set; }
        public string C_HL { get; set; }
        public string C_XM { get; set; }
        public Nullable<System.DateTime> D_DFPHL_START_TIME { get; set; }
        public Nullable<System.DateTime> D_DFPHL_END_TIME { get; set; }
        public Nullable<System.DateTime> D_KP_START_TIME { get; set; }
        public Nullable<System.DateTime> D_KP_END_TIME { get; set; }
        public Nullable<System.DateTime> D_HL_START_TIME { get; set; }
        public Nullable<System.DateTime> D_HL_END_TIME { get; set; }
        public Nullable<System.DateTime> D_PLAN_KY_TIME { get; set; }
        public string C_PLAN_ROLL { get; set; }
        public Nullable<System.DateTime> D_ZZ_START_TIME { get; set; }
        public Nullable<System.DateTime> D_ZZ_END_TIME { get; set; }
        public Nullable<System.DateTime> D_XM_START_TIME { get; set; }
        public Nullable<System.DateTime> D_XM_END_TIME { get; set; }
        public string C_STOVE_NO { get; set; }
        public Nullable<System.DateTime> D_DFPHL_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_DFPHL_END_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_KP_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_KP_END_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_HL_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_HL_END_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_XM_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_XM_END_TIME_SJ { get; set; }
        public Nullable<decimal> N_SJ_WGT { get; set; }
        public Nullable<System.DateTime> D_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_END_TIME_SJ { get; set; }
        public int N_DFP_HL_TIME { get; set; }
        public int N_HL_TIME { get; set; }
        public string C_ROUTE { get; set; }
        public Nullable<decimal> N_SLAB_PW { get; set; }
        public string C_MATRL_CODE_KP { get; set; }
        public string C_MATRL_NAME_KP { get; set; }
        public string C_KP_SIZE { get; set; }
        public Nullable<long> N_KP_LENGTH { get; set; }
        public Nullable<decimal> N_KP_PW { get; set; }
        public Nullable<short> N_USE_WGT { get; set; }
        public Nullable<System.DateTime> D_USE_START_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_USE_END_TIME_SJ { get; set; }
        public Nullable<System.DateTime> D_CAN_USE_TIME { get; set; }
        public Nullable<short> N_RH_NUM { get; set; }
        public Nullable<decimal> N_KP_WGT { get; set; }
        public Nullable<decimal> N_XM_WGT { get; set; }
        public string C_DFP_RZ { get; set; }
        public string C_RZP_RZ { get; set; }
        public string C_DFP_YQ { get; set; }
        public string C_RZP_YQ { get; set; }
        public string C_STL_GRD_TYPE { get; set; }
        public string C_PROD_KIND { get; set; }
        public string C_TL { get; set; }
        public Nullable<short> N_JSCN { get; set; }
        public string C_FREE1 { get; set; }
        public string C_FREE2 { get; set; }
        public Nullable<short> N_GROUP { get; set; }
        public string C_FK { get; set; }
        public Nullable<decimal> N_ZJCLS { get; set; }
        public Nullable<decimal> N_ZJCLS_MIN { get; set; }
        public Nullable<decimal> N_ZJCLS_MAX { get; set; }
        public string C_SL { get; set; }
        public string C_WL { get; set; }
        public string C_SLAB_TYPE { get; set; }
        public Nullable<decimal> N_JC_SORT { get; set; }
        public string C_LF { get; set; }
        public string C_KP { get; set; }
        public string C_REMARK1 { get; set; }
        public string C_REMARK2 { get; set; }
        public string C_REMARK3 { get; set; }
        public string C_REMARK4 { get; set; }
        public string C_REMARK5 { get; set; }
        public Nullable<decimal> N_KP_SORT { get; set; }
        public Nullable<decimal> N_XM_SORT { get; set; }
        public string C_KP_ID { get; set; }
        public string C_XM_ID { get; set; }
        public Nullable<System.DateTime> D_KP_CAN_START_TIME { get; set; }
        public Nullable<System.DateTime> D_XM_CAN_START_TIME { get; set; }
        public Nullable<decimal> N_KP_JRL_HOUR { get; set; }
        public string C_DQ_ORDER { get; set; }
        public Nullable<decimal> N_NEW_STATUS { get; set; }
        public Nullable<decimal> N_KP_STATUS { get; set; }
        public Nullable<decimal> N_XM_STATUS { get; set; }
        public Nullable<decimal> N_DHL_STATUS { get; set; }
        public Nullable<decimal> N_HL_STATUS { get; set; }
        public Nullable<decimal> N_ORDER_WGT { get; set; }
        public string C_BXGGZ { get; set; }
        public Nullable<short> N_SFKPPC { get; set; }
    
        public virtual TSP_CAST_PLAN TSP_CAST_PLAN { get; set; }
    }
}
