//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TEST
    {
        public string C_TT1 { get; set; }
        public string C_TT2 { get; set; }
        public string C_TT3 { get; set; }
        public Nullable<decimal> C_TT4 { get; set; }
        public decimal C_TT5 { get; set; }
        public string C_TT6 { get; set; }
    }
}
